### ISSUE TITLE
Hexo server fails to start (events.js:72) with grunt-bower package

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/tranquilpeak-hexo-theme#1]
When I'm trying to start the server with ```hexo s```, the followed error message appears :  
``` javascript
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: UNKNOWN, open '/Volumes/HDD/Users/louis/hexo-blog/themes/tranquil-peak/node_modules/grunt-bower/node_modules/bower/node_modules/update-notifier/node_modules/configstore/node_modules/js-yaml/node_modules/argparse/node_modules/lodash/array/tail.js'
```  
  
The problem comes from ```grunt-bower``` package. When I delete the ```/Volumes/HDD/Users/louis/hexo-blog/themes/tranquil-peak/node_modules/grunt-bower/``` folder, the server manage to start.  
  
I have already reported this issue on **hexojs/hexo** repository : [issues#1210](https://github.com/hexojs/hexo/issues/1210).

**Comment by iPonyo** [comment]
Hi !  Can you tell me the thumbnailImage should be put in which folder？
Sorry, i am not good at englist !   : )
Thanks !

**Comment by LouisBarranqueiro** [comment]
I got this error only when i try to start the hexo server with the terminal integrated to my IDE (InteliJ IDEA 14.1.3). When i start the server with the terminal of my OS (MAX OS X Yosmite 10.10.3), it's work fine!
