### ISSUE TITLE
No styles for images

### ISSUE THREAD

**Issue by perry-mitchell** [LouisBarranqueiro/tranquilpeak-hexo-theme#102]
I'm trying to show an image, like so:
```
{% image fig-25 left clear http://perrymitchell.net/wp-content/uploads/2015/05/iOS-Simulator-Screen-Shot-16-May-2015-6.10.54-pm-e1431790537554.png %}
```

The generated source is correct:
```
<img src="http://perrymitchell.net/wp-content/uploads/2015/05/iOS-Simulator-Screen-Shot-16-May-2015-6.10.54-pm-e1431790537554.png" class="fig-25 left clear">
```

The styles that should be supporting the image (fig-25, left, clear) are not present in the document in any stylesheet:
<img width="351" alt="screen shot 2015-09-28 at 10 52 38 pm" src="https://cloud.githubusercontent.com/assets/3869469/10146875/af20d228-6633-11e5-88b6-e345f0ae579e.png">

I'm using the latest copy of the theme and Hexo..

**Comment by h404bi** [comment]
I made a fresh test. It works fine. Please post your two config files(hexo `_config.yml` and theme `_config.yml`).
![default](https://cloud.githubusercontent.com/assets/5764917/10153241/0af6e796-668d-11e5-98db-2ae5366531b6.PNG)

**Comment by LouisBarranqueiro** [comment]
Is it good @perry-mitchell ? :)

**Comment by perry-mitchell** [comment]
Unfortunately no.. I'm still puzzled as to why there's a lack of styles.

The lines:

```
{% image fig-50 left http://perrymitchell.net/wp-content/uploads/2015/05/iOS-Simulator-Screen-Shot-16-May-2015-6.10.54-pm-e1431790537554.png %} _The Sudoku game in the Aivoterveydeksi! iOS app with coloured pieces._

{% image fig-50 left clear http://perrymitchell.net/wp-content/uploads/2015/05/iOS-Simulator-Screen-Shot-16-May-2015-6.11.44-pm-e1431790511257.png %} _The Sudoku game in the Aivoterveydeksi! iOS app with coloured pieces, notes and an incorrect move._
```

Generate the following:
<img width="1392" alt="screen shot 2015-10-05 at 8 19 36 pm" src="https://cloud.githubusercontent.com/assets/3869469/10287907/7a7914b6-6b9e-11e5-8ee7-3be912e366d0.png">

As you can see, there's no `div`s and no fig-50 styles coming though.

**Comment by LouisBarranqueiro** [comment]
What version of tranquilpeak, do you have? Did you only copy scripts to use tags from version 1.3 in an old version ?
It doesn't work because you don't have the right html structure. Here is what it's suppose to be :  
![capture d ecran 2015-10-05 a 19 46 21](https://cloud.githubusercontent.com/assets/4705626/10288594/10d09a4c-6b9a-11e5-9015-986263d48d1c.png)

**Comment by h404bi** [comment]
Only I can reproduce his generated source is by using the `{% img %}` tag (hexo default tag block). I think there maybe something wrong between `{% img %}` tag and `{% imgae %}` tag in his hexo instance.

**Comment by perry-mitchell** [comment]
I'm using version 1.2.0 of the theme, which was downloaded very recently. I see that 1.3.0 is out, which I can try updating to.

**Comment by LouisBarranqueiro** [comment]
**image** and **wide_image** tag are only available in version 1.3.0. That why you don't have the right style. you have to update to [version 1.3.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.3.0)

**Comment by perry-mitchell** [comment]
Thanks @LouisBarranqueiro - I'm trying to upgrade now. I've replaced the tranquilpeak folder with the latest 1.3.0 version, filled in the _config.yaml file, and have cleaned and generated in the main hexo dir. None of my js or other assets can be found though:
<img width="449" alt="screen shot 2015-10-09 at 7 18 47 pm" src="https://cloud.githubusercontent.com/assets/3869469/10399317/9d4dad98-6eba-11e5-99c4-c5d1c3e39a73.png">

And it seems that the directory is empty:
<img width="627" alt="screen shot 2015-10-09 at 7 16 37 pm" src="https://cloud.githubusercontent.com/assets/3869469/10399290/804d4190-6eba-11e5-964e-ff88761e6e86.png">

Whereas in the old theme directory it had them:
<img width="829" alt="screen shot 2015-10-09 at 7 16 20 pm" src="https://cloud.githubusercontent.com/assets/3869469/10399294/89fcef4c-6eba-11e5-833d-3a31aea15745.png">

What am I doing wrong? I bower-installed already in the theme dir, which installed font-awesome etc., but it doesn't seem to have helped at all.

**Comment by LouisBarranqueiro** [comment]
Because you downloaded the source and not the built version.
Option 1:
- build the theme -> read developer documentation to know how to do that
- download the built version [here](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.3.0)

I wrote a good documentation and a README please read them :D

**Comment by perry-mitchell** [comment]
That's very true, sorry!

The images are working correctly now, thanks a lot for the help.

**Comment by LouisBarranqueiro** [comment]
Your welcome :D
