### ISSUE TITLE
Can't update author's bio and job

### ISSUE THREAD

**Issue by brucehan77** [LouisBarranqueiro/tranquilpeak-hexo-theme#103]
In _config.yml, I wrote like this: 
![2015-09-28 8 00 53](https://cloud.githubusercontent.com/assets/7897591/10154454/2b0cb1da-661c-11e5-9792-8c9487712bb2.png)
But the information can't be updated:
![2015-09-28 8 01 23](https://cloud.githubusercontent.com/assets/7897591/10154463/43d612ba-661c-11e5-897c-852f022d7dc5.png)

Thanks

**Comment by h404bi** [comment]
Em, should fill into the [language file](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/languages/en.yml#L44)
https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/_config.yml#L104

**Comment by brucehan77** [comment]
It works, thx.

**Comment by LouisBarranqueiro** [comment]
Thanks you @h404bi for your contribution :)

**Comment by Mmmu** [comment]
I've fill the author bio and job in en.yml, and set language to en,
the result is I can see my bio and job in localhost, but not after deployment.
I can't see the bio and job at myusername.github.io after days.

**Comment by LouisBarranqueiro** [comment]
open a new issue with your theme version, hexo version, OS information and hexo-deployer used, please.
