### ISSUE TITLE
Images and links not rendering in some excerpts

### ISSUE THREAD

**Issue by jbcpollak** [LouisBarranqueiro/tranquilpeak-hexo-theme#108]
I have a post with these contents:

```
[![The China Exim Corvette alone at the FIA GT1 Championship in Beijing](http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/i-JS8KS5s/0/M/All-Alone-M.jpg "All Alone")](http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/18995038_thTJxj#1475626489_JS8KS5s-A-LB)

[Click here to see the whole album](http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/18995038_thTJxj#1475626489_JS8KS5s).
```

Which should render like this on the home page:

The GT1 Championship this weekend was a pretty soggy affair, but I got to take some photos…

[![The China Exim Corvette alone at the FIA GT1 Championship in Beijing](http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/i-JS8KS5s/0/M/All-Alone-M.jpg "All Alone")](http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/18995038_thTJxj#1475626489_JS8KS5s-A-LB)

[Click here to see the whole album](http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/18995038_thTJxj#1475626489_JS8KS5s).

But instead renders like this:

The GT1 Championship this weekend was a pretty soggy affair, but I got to take some photos… Click here to see the whole album. 

(Notice no formatting, no image, and no links).

In this case the entire post fits within the excerpt length limit, and I don't have a `<!-- more -->` tag.

Am I don't something wrong?

**Comment by jbcpollak** [comment]
On a related note, and related to #89, is there any way to _disable_ excerpting? I would like to force some posts to be included in their entirety on the index page.

**Comment by Imyssed** [comment]
Just add some code by yourself~
```
                <div class="postShorten-excerpt" itemprop="articleBody">
                    <% if (post.excerpt) { %>
                        <%- post.excerpt %>
                    <% } else { %> // here
                        **<% if (post.full) { %>
                          <%- post.content %>
                        <% } else { %>**
                        <p>
                            <%- post.content.replace(/<(?:.|\n)*?>/gm, '').substr(0, 200) %><br>
                    <% } %>
```

**Comment by LouisBarranqueiro** [comment]
You are in a case that I hadn't anticipate. You are not using `<!-- more -->`, and the theme automatically cut the post content but the output isn't rendered! I will fix that.

**Comment by jbcpollak** [comment]
Thank you!

**Comment by jbcpollak** [comment]
I also noticed that for many posts the automatically truncated output was
cut off mid word. I don't know if that is related or something you can fix,
but I was expecting truncation at the end of a word with ellipsis at the
end.

**Comment by LouisBarranqueiro** [comment]
Yeah, it can be an idea, but I recommend to use `<!-- more -->` tag and soon the `excerpt` front matter variable.

**Comment by jbcpollak** [comment]
OK that makes sense. With the fix you mentioned, what would be the changed
behavior?

**Comment by LouisBarranqueiro** [comment]
Like the commit said :p tranquilpeak will render (markdown engine) the automatic post exceprt

**Comment by jbcpollak** [comment]
@LouisBarranqueiro  - sorry, I wasn't following the thread in my email and I didn't realize a commit had been made (I didn't get an email about it!) - I'll check it out now!

**Comment by LouisBarranqueiro** [comment]
np :D

**Comment by jbcpollak** [comment]
With your commit I get this result:

```
The GT1 Championship this weekend was a pretty soggy affair, but I got to take some photos…

<a href=”http://www.joshpollak.com/Cars/Racing/2011-FIA-GT1-Beijing/18995038_thTJxj#1475626489_JS8
```

When you truncate before rendering the markdown, I guess you can end up with invalid code which can't be rendered.

I tried changing the code to be the following, and it works a _bit_ better:

```
                    <% if (post.excerpt) { %>
                        <%- post.excerpt %>
                    <% } else { %>
                        <p>
                            <%- function(s) {
                                   var maxLen = 200;
                                   var content = markdown(s);
                                   var toLong = content.length>maxLen;
                                   var s_ = toLong ? content.substr(0,maxLen-1) : content;
                                   return s_.substr(0,s_.lastIndexOf(' ')) + " &hellip;";
                                }(post.content)
                             %><br>
                    <% } %>
```

This truncates the code (on a word boundary) _after_ rendering to markdown. The plus side is this doesn't look too bad, the downside is you are truncating including counting the HTML, so anchor tags, etc, get counted in your word count.

So a post like this:

I have [previously posted](http://www.offthehill.org/articles/2010/12/31/macfuse-for-64-bit-snow-leopard "MacFuse for 64-bit Snow Leopard") about using MacFuse with Snow Leopard, but if you have already upgraded to **OS X Lion**, you may be having trouble finding a version of FUSE to use.

Gets rendered as:

I have [previously posted](http://www.offthehill.org/articles/2010/12/31/macfuse-for-64-bit-snow-leopard "MacFuse for 64-bit Snow Leopard") about ...

The post about the car image above works ok, but the image doesn't appear.

Then I tried this small change:

```
                    <% if (post.excerpt) { %>
                        <%- post.excerpt %>
                    <% } else { %>
                        <p>
                            <%- function(s) {
                                   var maxLen = 200;
                                   var content = s;
                                   var toLong = content.length>maxLen;
                                   var s_ = toLong ? content.substr(0,maxLen-1) : content;
                                   return markdown(s_.substr(0,s_.lastIndexOf(' ')) + " &hellip;");
                                }(post.content)
                             %><br>
                    <% } %>
```

This gives the same result with the MacFuse post, but truncates the race car post in the middle of the anchor tag:

The GT1 Championship this weekend was a pretty soggy affair, but I got to take some photos…

<a …

**Comment by jbcpollak** [comment]
What I think I would really like is the ability to disable excerpting completely for certain posts. It seems like automated 200-character truncation can't be done cleanly pre or post markdown rendering so using `<!-- more -->` or the 'excerpt' front-matter makes a lot of sense, but what about when you don't want an excerpt at all? 

I could use `<!-- more -->` at the bottom of the post, but if there is nothing more to add, I really don't want to have a 'continue reading' link.

**Comment by LouisBarranqueiro** [comment]
Yeah, clearly, It seems to be the better solution. If `excerpt` variable isn't defined in front-matter and `<!-- more -->` doesn't exist in post content so post content will be displayed.

**Comment by jbcpollak** [comment]
Yeah, I think manually setting the excerpt is the only safe way to go. Is `post.excerpt` set by hexo or tranquilpeak? I couldn't find where it was being determined.

**Comment by LouisBarranqueiro** [comment]
But I'am not clearly convicted in terms of UX & UI. What is your problem currently? You just wanna display some images and link in post excerpt but not the all content?

**Comment by jbcpollak** [comment]
No, the problem its its a short post, but longer than 200 characters, or with an image. See here:

http://code.joshpollak.com/blog/

Compare the FIA GT1 post on that page to how it looks on its own page:

http://code.joshpollak.com/2011/09/12/fia-gt1-championship-in-beijing/

And how these longer posts get truncated on the main page:

http://code.joshpollak.com/2011/07/21/macfuse-for-os-x-lion/
http://code.joshpollak.com/2011/06/03/java-static-variables-are-wrong-almost-always/

I really like the look of tranquilpeak with the short excerpts on the main page, but when migrating a blog or writing long posts, the hard-truncation seems to cause a lot of problems.

**Comment by LouisBarranqueiro** [comment]
Check the new feature :) I will release the new version this sunday

**Comment by jbcpollak** [comment]
I reviewed the code, but I don't think I get it. :/

**Comment by LouisBarranqueiro** [comment]
?

**Comment by LouisBarranqueiro** [comment]
I just released the new version [1.4.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.4.0), read user doc - [define post excerpt](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#define-post-excerpt) and [display all post excerpt content](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#display-all-post-content) sections

You should be able to do what you want now. Re-open the issue, if you encounter some problem

**Comment by jbcpollak** [comment]
Looks great, I'll try it out!

**Comment by LouisBarranqueiro** [comment]
Yeah, tell me :)

**Comment by jbcpollak** [comment]
Works great! This is how I'd like it to work. I'm a bit worried this might cause you some trouble with other users since the default behavior has changed (excerpts aren't automatic anymore), but I think its the best solution.

**Comment by LouisBarranqueiro** [comment]
yes, it's better than auto excerpt because it give more possibilities to the user. Thank you for created this issue :D
