### ISSUE TITLE
Something wrong with the arrow buttom.

### ISSUE THREAD

**Issue by JolsonZhu** [LouisBarranqueiro/tranquilpeak-hexo-theme#109]
Thank you very much for sharing your Tranquilpeak-hexo-theme demo with us. It is of great help. 

But just now I found a bug when I was previewing the blog on my 4-inch-screen iPhone 5. The right arrow button at the bottom, which linked to the next article, was half covered just as shown in the picture followed. 
![1](https://cloud.githubusercontent.com/assets/12669627/10262105/1608bab6-69ed-11e5-97b7-c1507cd26b41.png)

When I rolled down to the bottom of the page, the problem still existed.
![2](https://cloud.githubusercontent.com/assets/12669627/10262110/25313522-69ed-11e5-9e48-935ae78d9203.png)

 Then I used a 5-inch-screen Android Phone. This time the right arrow button was completely missing, and the right side of the screen was empty.
![3](https://cloud.githubusercontent.com/assets/12669627/10262111/29dd502e-69ed-11e5-92e1-dd890e293eae.png)

 However it turned all right when I rolled down to the bottom. 
![4](https://cloud.githubusercontent.com/assets/12669627/10262112/2f05dd82-69ed-11e5-9950-e79ea12c5aef.png)

Many thanks for your theme again and I look forward to your next excellent theme.

**Comment by LouisBarranqueiro** [comment]
hummm, very strange behavior. which version of safari do you have? It works well Safari 8 and Safari 9 : 
![capture d ecran 2015-10-03 a 20 34 23](https://cloud.githubusercontent.com/assets/4705626/10264516/4f2c8694-6a0e-11e5-9e94-68f56978f258.png)

**Comment by JolsonZhu** [comment]
Yes,  it's Safari 7, and I'm not sure if this theme is compatible with Safari 8 or later versions.

**Comment by LouisBarranqueiro** [comment]
It's compatible with Safari 8 and 9.

**Comment by JolsonZhu** [comment]
OK, thank you very much.
