### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by haichao592** [LouisBarranqueiro/tranquilpeak-hexo-theme#11]
Hey, the URL of my blog is: [haichao.me](http://haichao.me)
Maybe I can offer help to Chinese users to customize the theme that satisfies their habbits.

**Comment by LouisBarranqueiro** [comment]
What do you mean?  
I have already added you blog into showcase.

**Comment by haichao592** [comment]
oh，sorry！
I think my first issue about this theme has a wrong title that has no concern about the issue's content.So I ask to add my site officially with the right title.
Sorry to bother you😁

**Comment by LouisBarranqueiro** [comment]
no problem. :D
