### ISSUE TITLE
Code rendering with 1 line number when language is not specified

### ISSUE THREAD

**Issue by aidanhs** [LouisBarranqueiro/tranquilpeak-hexo-theme#110]
You can see this at http://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/2014/10/29/Tags-plugins-showcase/#With_caption_and_URL

There are two lines there, but only 1 line number! Adding `lang:java` (or any recognised language) appears to fix it.

Not sure if this is a hexo or tranquilpeak issue?

**Comment by LouisBarranqueiro** [comment]
I think the problem come from Highlight.js or Hexo.

**Comment by LouisBarranqueiro** [comment]
Try with an other theme but I think It will be the same
