### ISSUE TITLE
Avatar Image goes wrong when using direct image url.

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#111]
Look like the following
![image](https://cloud.githubusercontent.com/assets/3963397/10330816/e9f94602-6d02-11e5-90a7-bc6852b42c52.png)

I have set the domain url to 
![image](https://cloud.githubusercontent.com/assets/3963397/10330832/09e0ad70-6d03-11e5-88a6-4d368159c242.png)

**Comment by h404bi** [comment]
You should put your avatar image into `assets/images/`, and use relative url.
![20151007150104](https://cloud.githubusercontent.com/assets/5764917/10331019/74666ddc-6d04-11e5-9220-1d365a186f3c.png)

In [layout/_partial/about.ejs](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/layout/_partial/about.ejs#L9), it generates url with `theme.image_dir`, which is set in theme [`_conifg.yml`](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/_config.yml#L13).

Or yourself edit the source, remove : 
``` html
<img id="about-card-picture" src="<%- theme.author.picture %>"/>
```

**Comment by LouisBarranqueiro** [comment]
yeah, curently you can't use an external image for your avatar. I will fix that :) I'im going to try to release a new version this WE :)

**Comment by LouisBarranqueiro** [comment]
feature added :)

**Comment by h404bi** [comment]
@LouisBarranqueiro the regex look really complex, D:, why not just use `.indexOf('://') >= 0`.

**Comment by LouisBarranqueiro** [comment]
Yeah, the `.indexOf('://')` do the job like I did in `sidebar.ejs`, but the regex improve the control of the url and I think the performance are not so much impacted since the string is not so long. I will do some tests to check that.

**Comment by LouisBarranqueiro** [comment]
I will change to `.indexOf('://')`, I used this method a lot of time in this theme to test external url so... :)
