### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by qetr1ck-op** [LouisBarranqueiro/tranquilpeak-hexo-theme#112]
Hi Louis,
first of all, thanks for your theme for hexo, you did a big job.

I have a question about search feature, because it didn't work out of box. But in yours example, it works pretty well.
I didn't see any partial md, js, or even scss files in sources, which should be related to this feature. Also didn't find anything about configure "search" in your docs.

Did I miss something?

Thanks for future clarification.

**Comment by LouisBarranqueiro** [comment]
Hi man, Thank you. I really appreciate! :) 

Search feature is handled by [Swiftype](https://swiftype.com). You can use it by filled `swiftype_install_key` in theme configuration file and that's it! :)

**Comment by qetr1ck-op** [comment]
It was my stupid inattention...=)

Again thanks for a flash-fast response.
Have an amazing Friday =)

**Comment by LouisBarranqueiro** [comment]
no problem man, you too :D
