### ISSUE TITLE
Deployment at OpenShift

### ISSUE THREAD

**Issue by mazeryt** [LouisBarranqueiro/tranquilpeak-hexo-theme#113]
Maybe it is dumy question but I am trying to deploy my own blog using openshift, but first of all I am trying to deploy Your template.

For configuration I use github repo from hexo:
https://github.com/openshift-quickstart/hexo-openshift/blob/master/package.json

to this configuration I added:

     "dependencies": {
        "font-awesome": "~4.3.0",
        "jquery":      "~2.1.3",
        "fancybox":    "~2.1.5",
        "express": "~3.4.4"
      },
      "devDependencies": {
        "bower":                "^1.3.12",
        "grunt":                "^0.4.5",
        "grunt-bower":          "^0.18.0",
        "grunt-contrib-clean":  "~0.5.0",
        "grunt-contrib-concat": "^0.5.0",
        "grunt-contrib-copy":   "~0.4.1",
        "grunt-contrib-cssmin": "^0.12.0",
        "grunt-contrib-uglify": "^0.7.0",
        "grunt-contrib-watch":  "^0.6.1",
        "grunt-sails-linker":   "^0.10.1",
        "grunt-sass":           "1.0.0",
        "grunt-sync":           "^0.2.3",
        "grunt-text-replace":   "^0.4.0",
        "include-all":          "^0.1.6",
        "load-grunt-tasks":     "~0.2.0"
        },

With those changes and without them my blog is not deployed successfully because of not found errors:

    Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/tranquilpeak.css Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/jquery.fancybox-thumbs.css Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/js/jquery.js Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/js/jquery.fancybox.js Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/js/jquery.fancybox-thumbs.js Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/js/tranquilpeak.js Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/jquery.fancybox.css Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/font-awesome.css Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/jquery.fancybox.css Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/jquery.fancybox-thumbs.css Failed to load resource: the server responded with a status of 404 (Not Found)
    http://test-skirki.rhcloud.com/assets/css/tranquilpeak.css Failed to load resource: the server responded with a status of 404 (Not Found)

Any Idea what can be fixed to make deployment working?

**Comment by LouisBarranqueiro** [comment]
Did you download the source or the built version?

**Comment by mazeryt** [comment]
I only based at downloaded sources as github repo
 
What I did is deploy standard hexo from github and it works as well with default template then i put git submodule into repository with tranquilpeak into themes as a tranquilpeak folder and change theme in scheme _config.yml from landscape into tranquilpeak.
The problem with openshift is that You cannot run 
    
     npm install 

Because of permissions so i trying add dependencies and I saw that openshift were downloading them (in exapmle jquerry, fonts and so on) but later as You see there are not found by root.

**Comment by LouisBarranqueiro** [comment]
When you download the source theme, you have to build the theme. If you don't want or can't do that, download the built version [here](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.3.0).

**Comment by mazeryt** [comment]
Thanks for tips. I am trying to create blog but I am not familiar with these kind of web development so I was a little confused but I will read documentation. Thanks

**Comment by LouisBarranqueiro** [comment]
Your welcome :) the documentation is here for that :D
