### ISSUE TITLE
Why can't I generate asset folder and CSS could not load?

### ISSUE THREAD

**Issue by irmowan** [LouisBarranqueiro/tranquilpeak-hexo-theme#116]
When I use hexo generate, I cannot find asset folder in public, but index.html use CSS which stores there. I don't know where I went wrong.

**Comment by irmowan** [comment]
When I use `hexo generate`, I cannot find `asset` folder in `public`, but `index.html` use CSS which stores there. I don't know where I went wrong.

**Comment by LouisBarranqueiro** [comment]
Please read [developer documentation build section](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/developer.md#build)

**Comment by irmowan** [comment]
After I run `bower install`, it returns. But I cannot see `_bower_components` in the folder `source`.
By the way, how to know my NPM dependencies?

**Comment by LouisBarranqueiro** [comment]
- run npm install -g bower
- run npm install -g hexo
- run npm install -g grunt-cli
- run npm install
- run bower install
- run grunt build

**Comment by irmowan** [comment]
Sorry, but it cannot find `Gruntfile` as I run `grunt build`

**Comment by LouisBarranqueiro** [comment]
Run the 3 last cmd in tranquilpeak folder

**Comment by irmowan** [comment]
Oh! It works! Thank you!!
