### ISSUE TITLE
PostShorten divs break lines in the middle of words

### ISSUE THREAD

**Issue by jbcpollak** [LouisBarranqueiro/tranquilpeak-hexo-theme#118]
It looks like the .postShorten classes have this css:

`word-break: break-all;`

This cases a line to break in the middle of a word, like this:

```
The quick brown fox jumped over the la
zy dog.
```

Is that intentional? I would expect:

```
The quick brown fox jumped over the 
lazy dog.
```

**Comment by LouisBarranqueiro** [comment]
yeah, I did that to fix this : #62. but yeah, it created an other problem.

**Comment by jbcpollak** [comment]
I think you want to use overflow controls for that problem. Possibly `overflow: scroll`

StackOverflow used to have a similar problem with `<pre>` blocks, I forget how they solved it.

**Comment by LouisBarranqueiro** [comment]
It caused by long string like an url without `-` (in our case), I will remove this css property.
