### ISSUE TITLE
How to upgrade tranquilpeak?

### ISSUE THREAD

**Issue by rk2900** [LouisBarranqueiro/tranquilpeak-hexo-theme#119]
I've download the older version of this theme.
I wonder how I can upgrade this theme?

And where can I find the version number of the theme source which I'm using now?

3Q!

**Comment by LouisBarranqueiro** [comment]
There is actually no script to upgrade the version of Tranquilpeak. You have to do it manually.
1. Download the new version
2. Re-fill theme configuration file
3. Re-fill theme languages file used

You can find the version in package.json file

**Comment by rk2900** [comment]
I upgrade my 1.3.0 version to 1.4.0.
However, in the hexo server mode, my browser cannot find any css or js files.
So my page cannot be presented normally.
But when I change "tranquilpeak" folder into the 1.3.0 one, it works perfectly.
I've tried "hexo clean" first, but it doesn't work.

Could you please tell me how to solve it?

**Comment by h404bi** [comment]
Do you download the source? https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases

**Comment by rk2900** [comment]
Ah my fault!

Thank you very much!
