### ISSUE TITLE
IT's no generation css

### ISSUE THREAD

**Issue by whj929159021** [LouisBarranqueiro/tranquilpeak-hexo-theme#121]
Run 'hexo g'
This log like this:
INFO  Files loaded in 375 ms
INFO  Generated: 2015/10/17/hello-world/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2015/index.html
INFO  Generated: archives/2015/10/index.html
INFO  Generated: index.html
INFO  5 files generated in 114 ms

This is hero package.json
  "dependencies": {
    "hexo": "^3.1.0",
    "hexo-generator-archive": "^0.1.2",
    "hexo-generator-category": "^0.1.2",
    "hexo-generator-index": "^0.1.2",
    "hexo-generator-tag": "^0.1.1",
    "hexo-renderer-ejs": "^0.1.0",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-renderer-marked": "^0.2.4",
    "hexo-server": "^0.1.2"
  }

Please help me, thinks!

**Comment by LouisBarranqueiro** [comment]
Could you give more details please?

**Comment by whj929159021** [comment]
I just installed hexo, In accordance with the "User documentation" configuration completed.
Run "hexo g", my blog directory no generation css file,only html file.

**Comment by LouisBarranqueiro** [comment]
Because, you downloaded source and not the built version. You have to build the theme. Please read developer documentation - build section.

**Comment by whj929159021** [comment]
Thank you very mach.It works properly.

**Comment by LouisBarranqueiro** [comment]
your welcome :)
