### ISSUE TITLE
The hexo can't generate css from your theme?

### ISSUE THREAD

**Issue by cnio** [LouisBarranqueiro/tranquilpeak-hexo-theme#123]
I follow the steps ,but can't load  CSS of the beautiful theme. May you have a check ?

**Comment by LouisBarranqueiro** [comment]
Thank man :)
You downloaded the source version. you have to build the theme. Read developer documentation - build section

**Comment by cnio** [comment]
Thanks,the problem was solved :+1:

**Comment by cnio** [comment]
Thanks,the problem was solved :+1:
