### ISSUE TITLE
asset folder was not generated when set post_asset_folder true

### ISSUE THREAD

**Issue by jmolboy** [LouisBarranqueiro/tranquilpeak-hexo-theme#125]
I had set post_asset_folder true,but asset folder was not generated,so all the static files(.js .css ) can not be loaded. I don't know the reason.pls help me

**Comment by LouisBarranqueiro** [comment]
post_asset_folder and global asset folder are not the same. I think you downloaded the source so you have to build the theme. Please read developer documentation - build section

**Comment by jmolboy** [comment]
Yes,you are right,I downloaded the source code.After builded it runs right.thank you very much.

**Comment by LouisBarranqueiro** [comment]
your welcome :)
