### ISSUE TITLE
categories link

### ISSUE THREAD

**Issue by tonyarash** [LouisBarranqueiro/tranquilpeak-hexo-theme#129]
I created a category with 3 words in it and on the all categories page the link has a space after the second word. Thus the link is broken. See here:
http://gymnear.com/blog/all-categories/

**Comment by LouisBarranqueiro** [comment]
yeah, you are right, the only first space is replaced by a "-". I will fix that. :)

**Comment by LouisBarranqueiro** [comment]
the patch is released : [v1.4.3](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.4.3). Thank you for feedback
