### ISSUE TITLE
Ruby and Sass are required to build tranquilpeak

### ISSUE THREAD

**Issue by haichao592** [LouisBarranqueiro/tranquilpeak-hexo-theme#13]
When I run `grunt Build` or `grunt sass` to build the theme or compile `scss` files, an warning shows that `You need to have Ruby and Sass installed and in your PATH for this task to work. It happens when ruby is not installed.

**Comment by haichao592** [comment]
Solution:
1. Install [ruby](https://www.ruby-lang.org/en/). For fedora users just run `yum install ruby`.
2. Run `gem install sass`.
Then you're done and you can build the theme without error.
PS: Even though `grunt-contrib-sass` will be installed when we run `npm install`, ruby and sass is still necessary to build the theme.

**Comment by LouisBarranqueiro** [comment]
Thank you, i'm working on to use only node.js dependencies. :)

**Comment by LouisBarranqueiro** [comment]
The version [1.0.2](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.0.2) resolve this issue. Thank you for the idea :)
