### ISSUE TITLE
homepage pagination

### ISSUE THREAD

**Issue by dmarg** [LouisBarranqueiro/tranquilpeak-hexo-theme#133]
Hi,

I just upgraded to the tranquilpeak v1.4.3 from v1.2 and the homepage is now not paginating. I see the full blog post on the front page and it does not stop it and add the continue reading like your demo page does.

Do you know what could be causing this?

**Comment by LouisBarranqueiro** [comment]
Since  1.4.x, the feature to automatically cut the post.content to display only the post excerpt on index page is removed. You have to use now `<!-- exceprt -->` or `<!-- more -->` comment in your post to cut it. read user documentation - writing section for more details

**Comment by dmarg** [comment]
Thanks! I will give that a try. 

Thanks for making this theme as it is really nice!

**Comment by LouisBarranqueiro** [comment]
Your welcome! Thank you man, I really appreciate! :)
