### ISSUE TITLE
can not preview the thumbnail image in localation

### ISSUE THREAD

**Issue by futurefeeling** [LouisBarranqueiro/tranquilpeak-hexo-theme#135]
in chrome brower take this

![image](https://cloud.githubusercontent.com/assets/9881593/10864143/549b708c-801f-11e5-9f92-1cfa8d1716b5.png)

so, weather it can not show the thumbnail image in localation?

and how can i write the direction?

and where can i put the picture?

I found some way to this problem in [customization](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#customization), and i put the picture in `/asset/images/` but it seems no render.

and my `Front-matter settings` like following:

``` 
title: 正式开始写博客
date: 2015-10-31 21:35:45
tags: 日记
categories: 随笔
clearReading: true
thumbnailImage: blog.png
thumbnailImagePosition: right
autoThumbnailImage: false
metaAlignment: center
comments: false
---
```

and in the file `_config.yml` the `url` value is my website

where i make a mistake?

uhhh, i use the latest version of your theme 1.4.3

**Comment by LouisBarranqueiro** [comment]
Could you give more details, please? I don't understand what you want to do? What is localation?

**Comment by LouisBarranqueiro** [comment]
Did you active the `post_asset_folder` to `true` in the main `_config.yml` file.

after this, create a folder in `source/_post` named `正式开始写博客` (name of your post) and put your image (blog.png) in this folder

**Comment by futurefeeling** [comment]
forgive my poor english, 'location'...

it means run in my pc without network

it works after i run `hexo d`. THKS!

but it still doesn't work without network.😢

**Comment by LouisBarranqueiro** [comment]
you have to set `url` to `http://localhost:4000`  and `root` to `/` parameter in `_config.yml`

**Comment by futurefeeling** [comment]
but if it changes, it will not work on internet after i ran `hexo d`.

and i mean some ways both fit running on my pc and running on internet...

😢sorry.... it you can speak Chinese , that would be great...

**Comment by LouisBarranqueiro** [comment]
before deploy your blog, you have to change the url

**Comment by futurefeeling** [comment]
👌， thanks a lot.Love you ,guy. specially your theme

**Comment by LouisBarranqueiro** [comment]
your welcome. Thank you man <3 :D
