### ISSUE TITLE
thumbnailImage,coverImage not support remote url in head meta.

### ISSUE THREAD

**Issue by jmolboy** [LouisBarranqueiro/tranquilpeak-hexo-theme#137]
when I set thumbnailImage&coverImage as a remote url,it's displaying right in the body,but not right in head meta[property="og:image"] .It seems using relative url here.

**Comment by jmolboy** [comment]
avatar in the head is the same.

**Comment by jmolboy** [comment]
page photos is the same.

**Comment by jmolboy** [comment]
I added code in head.ejs:



	function isremoteurl(url){
        if(url&&url.indexOf('://') >= 0){
            return true;
        }
        return false;
    }

    function imgurl(url){
        if(isremoteurl(url)){
            return url;
        }
        return url_for(page.permalink.replace('.html', '/') + url);
    }
    
    
<br/>  
edit all url_for(page.path.replace('.html', '/') +* 
to
imgurl(*)
  
	 <meta property="og:image" content="<%- imgurl(theme.author.picture) %>"/>

**Comment by jmolboy** [comment]
souce at [https://github.com/jmolboy/tranquilpeak-hexo-theme](https://github.com/jmolboy/tranquilpeak-hexo-theme)

**Comment by LouisBarranqueiro** [comment]
I will fix that! Thank you man :)

**Comment by jmolboy** [comment]
good
