### ISSUE TITLE
how about put google-analytics code at footer?

### ISSUE THREAD

**Issue by jmolboy** [LouisBarranqueiro/tranquilpeak-hexo-theme#140]
will it be better to put google-analytics code at page footer rather than at head? just for discussion :)

**Comment by LouisBarranqueiro** [comment]
Google recommends to put the code in the head. Check this for more details : http://stackoverflow.com/questions/3173571/should-i-put-the-google-analytics-js-in-the-head-or-at-the-end-of-body
