### ISSUE TITLE
Is there any way to add Number of times the post was tweeted or shared on fb ?

### ISSUE THREAD

**Issue by xerosanyam** [LouisBarranqueiro/tranquilpeak-hexo-theme#141]
I want to show how many times the post was shared on fb or on twitter.
Is there a way to do that ?

**Comment by LouisBarranqueiro** [comment]
Yeah, currently share buttons are simple html button without connection to facebook, twitter or google+. For example, to display Facebook share count : https://developers.facebook.com/docs/plugins/share-button

**Comment by xerosanyam** [comment]
Can you please provide steps to do that ?
I don't want to break how it renders on different form factor.

**Comment by LouisBarranqueiro** [comment]
I don't know mate, that why i gave you the Facebook developer documentation
