### ISSUE TITLE
sidebar

### ISSUE THREAD

**Issue by iPonyo** [LouisBarranqueiro/tranquilpeak-hexo-theme#142]
hi ! can you tell me how to make sidebar like this ? my theme  is short width(only icons), it's not what i want. thanks !
![d8eb57f5-5104-4284-a0b6-3d0d5e68fd59](https://cloud.githubusercontent.com/assets/2416322/11148708/4c27e9dc-8a59-11e5-9fe6-402f47ce13e3.png)

**Comment by LouisBarranqueiro** [comment]
Change `sidebar_behavior` variable in theme configuration file, read [user documentation - Theme configuration -> Customization](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#customization) for more details

**Comment by iPonyo** [comment]
Thanks ! :+1:
