### ISSUE TITLE
favicon not showing up

### ISSUE THREAD

**Issue by xerosanyam** [LouisBarranqueiro/tranquilpeak-hexo-theme#143]
even though I have set favicon.ico in _config.yml I am unable to see it load up in the browser

**Comment by LouisBarranqueiro** [comment]
Could you post your `_config.yml` file and your html page with a debug tool to show the source code, please?

**Comment by xerosanyam** [comment]
Sorry. I had some other issue. It's fixed now. Thanks :+1:

**Comment by LouisBarranqueiro** [comment]
good news :)
