### ISSUE TITLE
change logic in "Next article"

### ISSUE THREAD

**Issue by futurefeeling** [LouisBarranqueiro/tranquilpeak-hexo-theme#146]
![image](https://cloud.githubusercontent.com/assets/9881593/11232321/a84e9fe4-8dec-11e5-8352-c9e6745eb3bd.png)

see above photo

if i write this sentence in my article "Please pay attention to next article", my reader click the button "下一篇". But in fact, I found the "next article" in your theme is such article I wrote before, and the href of the button "previous article" is the real href what i need

....could you understand what i wanna to express  to?

**Comment by LouisBarranqueiro** [comment]
Sorry man, I don't understand. Did you mean that buttons are reversed?

**Comment by h404bi** [comment]
@LouisBarranqueiro He want the `next article` to newer article and `previous article` to older article. Now the `next article` to older article and `previous article` to newer article.

**Comment by LouisBarranqueiro** [comment]
Huuuuum, ok, I understand. :D  It's all about translations. What do you propose?  :)

**Comment by h404bi** [comment]
nope, i think current logic and translation are both no problem. Because AFAIK, other themes have the same logic.

**Comment by LouisBarranqueiro** [comment]
I think the same thing too. What do you propose @futurefeeling?

**Comment by futurefeeling** [comment]
sorry, busy to fix bug in some project recently. Maybe this is a different between eastern and western :D
