### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by RomanBogachev** [LouisBarranqueiro/tranquilpeak-hexo-theme#147]
Hi! 

I have read the previous issues, but did not find solutions in them for my question.
I want to use cyrillic fonts in my posts. I found Merriweather Cyrillic font.

I try to change `../tranquilpeak/source/_css_utils/_fonts.scss` where i replace links for a new font. (try locally or remotely)
Fonts put in `../tranquilpeak/source/_fonts` directory.

Also i try to change variables but nothing worked. 

How can i change it?

https://www.dropbox.com/s/pd8ieva0bv1t55f/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-11-18%2016.53.50.png?dl=0

**Comment by LouisBarranqueiro** [comment]
Did you build the theme?

**Comment by RomanBogachev** [comment]
No. Download as it is. 
I would like to do it without build or it is impossible?

**Comment by LouisBarranqueiro** [comment]
no, you can't. We you edit files in `sources/_*` folders, you are forced to build the theme

**Comment by RomanBogachev** [comment]
Ok. Thanks for your reply.
