### ISSUE TITLE
There is a bug in sidebar

### ISSUE THREAD

**Issue by yangfan-onion** [LouisBarranqueiro/tranquilpeak-hexo-theme#15]
![sidebar-bug](http://yangfan-onion.github.io/About-color/sidebar-bug.png)

When sidebar is up, I swipe the content to the left, then the content will appear at the bottom of sidebar, the scrollbar of web browser will display as well.

**Comment by LouisBarranqueiro** [comment]
Got it. I will fix this bug in version 1.0.3. :)

**Comment by LouisBarranqueiro** [comment]
The  [v1.0.3](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.0.3) is released and fix this bug. :)
