### ISSUE TITLE
Disqus script is outdated

### ISSUE THREAD

**Issue by billjh** [LouisBarranqueiro/tranquilpeak-hexo-theme#150]
Hi. First of all, thank you for the beautiful theme. But I found the embed script for Disqus is outdated and not working a few days ago. 

Refer to:
https://help.disqus.com/customer/portal/articles/472097-universal-embed-code

I wrote a post on my blog of my solution and it works for me. 
http://blog.moonlight.ml/2015/11/21/tranquilpeak-disqus/

Please take a look.

Cheers

**Comment by LouisBarranqueiro** [comment]
Thank you man! :) It still works on the demo site then I think the problem was something other. Let the issue open to see if other person have the same problem.

**Comment by LouisBarranqueiro** [comment]
I updated Disqus embedded script for the new version. :) 

I also notice that edited the theme to integrate the new script, but you did a mistake.
Here is the generated code : 
![capture d ecran 2015-12-13 a 21 02 16](https://cloud.githubusercontent.com/assets/4705626/11768958/db9ad59e-a1dc-11e5-9f50-8e766e11a781.png)
Check the commit that I did to get the right code.
