### ISSUE TITLE
how to delete tags?

### ISSUE THREAD

**Issue by cleechtech** [LouisBarranqueiro/tranquilpeak-hexo-theme#157]
I created some tags and then removed them. On the "all-tags" page the tags without posts will still show up

![screen shot 2015-11-29 at 11 53 04 am](https://cloud.githubusercontent.com/assets/3578908/11459644/0b86f47a-9690-11e5-9aaf-de6c0184f7b5.png)

How do I delete these phantom tags?

**Comment by LouisBarranqueiro** [comment]
Use `hexo clean` to delete the database `db.json`. and then re-generate your site with `hexo generate`

**Comment by cleechtech** [comment]
Works! Thank you
