### ISSUE TITLE
how to edit the font style of the posts

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#16]
Hi, Louis, thanks for your great job.
I had looked for hundreds of themes and find that yours is the best.
And now I would like to change the font style of the posts because the default style is not good for chinese characters.
Please offer a way.

**Comment by LouisBarranqueiro** [comment]
Thank you man! :) What do you mean by "offer a way" ? Do you mean : easily in `_config.yml`? or you want to know what css file you need to edit?

**Comment by kaedea** [comment]
Thanks Louis. "offer a way" means I want to edit the css (I am not a frontia developer therefore your answer is the fast way for me to edit).

**Comment by LouisBarranqueiro** [comment]
your welcome :)
