### ISSUE TITLE
add signup for email updates

### ISSUE THREAD

**Issue by cleechtech** [LouisBarranqueiro/tranquilpeak-hexo-theme#160]
I have a mailchimp list of email subscribers. I would like to add an input field so people can sign up to my email list through [my tranquilpeak blog](http://cleechtech.github.io/). How can I add a "subscribe to email updates" section to my blog?

I am thinking it could fit in the header, footer or sidebar. What is the best way to add a mailchimp signup form?

**Comment by cleechtech** [comment]
For mailchimp I got something like this:

```
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-081711.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//github.us5.list-manage.com/subscribe/post?u=0713e0ac2a414eae4ca4bb786&amp;id=0bdf2bdb00" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	<label for="mce-EMAIL">I'll be teaching new courses on Learn To Make Stuff With Code, sign up for updates here!</label>
	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0713e0ac2a414eae4ca4bb786_0bdf2bdb00" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
```

Not sure how I can drop this in

**Comment by LouisBarranqueiro** [comment]
You just have to add this code in the right view (header : `layout/partial/header.ejs`, footer : `layout/partial/footer.ejs`). That's all :)

**Comment by cleechtech** [comment]
My solution currently is to add the above embed to the compiled code after I run `hexo generate`. I add it in after `<div id="main" data-behavior="1" class="hasCoverMetaIn">` in the generated **index.html**. This works but I feel like it's not good to modify the source every time I generate. I think this is compounded by the problem that I have the theme as a git submodule, so direct changed to the theme (such as modifications to the CSS do not come through)

**Comment by cleechtech** [comment]
Ok that's where it will go. Thank you!

**Comment by wendingp** [comment]
So what is the best solution to this so far then?
