### ISSUE TITLE
No icons are shown in the Demo

### ISSUE THREAD

**Issue by dharma-guardian** [LouisBarranqueiro/tranquilpeak-hexo-theme#162]
The Sidebar Icons, as well as the open-sidebar and search icon in the mobile view, are not displayed.

```Javascript
script.min.js:1 Uncaught ReferenceError: jQuery is not defined(anonymous function) @ script.min.js:1
```

Further a request to swifttype fails.
I use Google Chrome Version 47.0.2526.73 (64-bit) on OSX 10.10.05 .
Great theme by the way...

**Comment by LouisBarranqueiro** [comment]
you forget to run `bower install`to install bower dependencies. don't forget to build the theme after that with `grunt build`or `grunt buildProd`. Read developer documentation for more information about how to build the theme

**Comment by dharma-guardian** [comment]
Sry, if I was too unclear. I speaking about the github pages demo.

**Comment by LouisBarranqueiro** [comment]
Yeah, because you didn't download dependencies. I supposed that you downloaded source and not built for [production version](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.4.3). When you download source, you have to build the theme. Read developer documentation.

**Comment by dharma-guardian** [comment]
I didn't download anything. I talk about your live demo, that I clicked in the description of your repository: http://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/
The problem is also present when I access it over Chrome on Android. 
Am 05.12.2015 3:58 nachm. schrieb Louis Barranqueiro <notifications@github.com>:Yeah, because you didn't download dependencies. I supposed that you downloaded source and not built for production version. When you download source, you have to build the theme. Read developer documentation.

**Comment by LouisBarranqueiro** [comment]
Oh yeah, you are right. I didn't understand that you were talking about the Tranquilpeak demo. It's fixed. Thank you :)
