### ISSUE TITLE
Comment Page

### ISSUE THREAD

**Issue by xiejiachen** [LouisBarranqueiro/tranquilpeak-hexo-theme#165]
How to add a comment page for gusets？

**Comment by xiejiachen** [comment]
I mean a guestbook, where guest can put comments and I can reply them

**Comment by LouisBarranqueiro** [comment]
Create a page with `hexo new page "your-page". and comments will be available if `disqus_shortname` is filled.

I just noticed that i did a mistake in the code that disable comment on page by default if page is not a post.Then update a line in `layout/_partial/script.ejs`:

replace this line
``` js
<% if (theme.disqus_shortname && is_post() && post.comments) { %>
```
with
``` js
<% if (theme.disqus_shortname && post.comments) { %>
```


I will fix this in next version.
