### ISSUE TITLE
Can I use other comment API other than disqus

### ISSUE THREAD

**Issue by xiejiachen** [LouisBarranqueiro/tranquilpeak-hexo-theme#166]
My apologize for disturb again:

However, the fact is disqus sometimes does not work within China mainland.( Maybe because goverment fire wall block.)

And some others templates also support other way same as disqus, which name is "duoshuo".
Can be found at https://github.com/duoshuo.

Below is the code.

<% if (!index && post.comments && config.duoshuo_shortname){ %>
  <section id="comments">
    
    <div class="ds-thread" data-thread-key="<%= post.layout %>-<%= post.slug %>" data-title="<%= post.title %>" data-url="<%= page.permalink %>"></div>
    
    
    <script type="text/javascript">
    var duoshuoQuery = {short_name:'<%= config.duoshuo_shortname %>'};
      (function() {
        var ds = document.createElement('script');
        ds.type = 'text/javascript';ds.async = true;
        ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
        ds.charset = 'UTF-8';
        (document.getElementsByTagName('head')[0] 
         || document.getElementsByTagName('body')[0]).appendChild(ds);
      })();
      </script>
    
  </section>
  <% } %>

The official document is I should import these codes into themes\tranquibreke\layout\partial\articles.esj, while I can not find it.

Is that possible I use this comment system in my web?
And hence it can be used with mainland.

Thanks for regarding.

**Comment by LouisBarranqueiro** [comment]
You question is is it possible to choose between disqus and duoshuo for comments system?

**Comment by xiejiachen** [comment]
yes

**Comment by LouisBarranqueiro** [comment]
you don't disturb me man :) I know that a user of this theme is using duoshuo. I will integrate it :) Will you be available to test the code with your duosho account?

**Comment by xiejiachen** [comment]
If I can , how to do it,  such as another templete Next
https://github.com/iissnan/hexo-theme-next/blob/master/README.en.md
Add the following snippets to your _config.yml:

duoshuo:
  enable: true
  shortname: your-duoshuo-shortname
OR

disqus:
   enable: true
   shortname: your-disqus-shortname

**Comment by xiejiachen** [comment]
I am just do not how to do it.
Sorry guy.

I am not good at CSS.

**Comment by xiejiachen** [comment]
Reply your last question: my duoshuo account have been tested, it works with template Next

**Comment by xiejiachen** [comment]
It does not work. I tried, infact if you are happy, I can help you create a duoshuo account and short_name respecitive to your test web. If you would like to do it, please give me your test web url

**Comment by xiejiachen** [comment]
my web is: xiejiachen.github.io

**Comment by LouisBarranqueiro** [comment]
I committed. That's right, it should works. :) https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/commit/94e760374842373e09c3ca037ebf42579571d432

**Comment by xiejiachen** [comment]
I will try again, just one moment

**Comment by LouisBarranqueiro** [comment]
It works for me :)

**Comment by xiejiachen** [comment]
Can I directly download your fixed codes?
It can only be done by copy from raw?

**Comment by LouisBarranqueiro** [comment]
just update the file  in `layout/_partial/script.js` : https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/commit/94e760374842373e09c3ca037ebf42579571d432

**Comment by xiejiachen** [comment]
Dear Louis,
    actually, how to only upadate singile file.

To update this file, actullay I have clone all folder files

**Comment by LouisBarranqueiro** [comment]
open the file in a IDE or a text editor and update the right line :D

**Comment by xiejiachen** [comment]
:0 lovely.
I just think maybe some more easier way......

**Comment by LouisBarranqueiro** [comment]
That's the easiest way :D

**Comment by xiejiachen** [comment]
Brother.
I promise, there exists some error with you fixed codes.
I tried a lot of times.

Yes, it works.
However, it is not my duoshuo_account. But others, I think maybe it because you refere others web codes and caused this error.

**Comment by LouisBarranqueiro** [comment]
comments aren't available on :  
- index page
- all-categories page
- all-tags page
- archives page
- archive page

if you wanna add comments on these pages, you have to edit the code.
