### ISSUE TITLE
Mac OS language problem

### ISSUE THREAD

**Issue by xiejiachen** [LouisBarranqueiro/tranquilpeak-hexo-theme#168]
Dear Louis:

    Your template perfect running with Windows.

    However, I tried to also set an web with mac OS.

By setting config
language: zh-cn

It still show with french.
 What is the problem?

**Comment by xiejiachen** [comment]
nothing. fixed it I did something wrong

**Comment by LouisBarranqueiro** [comment]
Is it fixed?

**Comment by xiejiachen** [comment]
Fixed
