### ISSUE TITLE
Fail in use your theme

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#17]
Hi, Louis. Thanks for your project.
I got a problem using your theme in hexo. The following is what I had done.

- clone your theme
- rename the root folder as "tranquilpeak" 
- edit the hexo conf file's attribute: `theme: tranquilpeak`
- hexo g, hexo s

But I got a wrong page like the following. It seems that the style file did not go right.
I don't know what I did is wrong. Maybe you can help.

![img](https://lh3.googleusercontent.com/-GrP06bnQt9I/VV7n2csHOPI/AAAAAAAABDg/A8Z6nUoLDCc/s0/QQ%25E6%2588%25AA%25E5%259B%25BE20150522162236.jpg)

**Comment by LouisBarranqueiro** [comment]
You downloaded the developer version so you have to build the theme to use it.  
To do that, bower and grunt must installed in global with `-g`parameter. 
1. run `npm install bower -g`
2. run `npm install grunt-cli -g`

After that :
1. run `npm install`
2. run `bower install`
3. run `grunt buildProd`

Please read [developer documentation](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/developer.md#build) Build part for more information.

**Comment by chenkaiC4** [comment]
I really like this theme! thanks for your best work ~ 
I read user doc, and then  developer doc, and type `grunt build` in my console, I got error, and my blog looks roughly, I found the reason: lack of css file.  

error info as follow:
```
Loading "sass.js" tasks...ERROR
>> Error: `libsass` bindings not found in /Users/chenkai/myBlog/blog/themes/tranquilpeak/node_modules/grunt-sass/node_modules/node-sass/vendor/darwin-x64-11/binding.node. Try reinstalling `node-sass`?

Running "clean:build" (clean) task
Cleaning source/assets...OK

Running "bower:dev" (bower) task
source/assets/images/blank.gif copied.
source/assets/images/fancybox_loading.gif copied.
source/assets/images/fancybox_loading@2x.gif copied.
source/assets/images/fancybox_overlay.png copied.
source/assets/images/fancybox_sprite.png copied.
source/assets/images/fancybox_sprite@2x.png copied.
source/assets/js/jquery.fancybox.js copied.
source/assets/css/jquery.fancybox.css copied.
source/assets/css/jquery.fancybox-thumbs.css copied.
source/assets/js/jquery.fancybox-thumbs.js copied.
source/assets/css/font-awesome.css copied.
source/assets/fonts/FontAwesome.otf copied.
source/assets/fonts/fontawesome-webfont.eot copied.
source/assets/fonts/fontawesome-webfont.svg copied.
source/assets/fonts/fontawesome-webfont.ttf copied.
source/assets/fonts/fontawesome-webfont.woff copied.
source/assets/fonts/fontawesome-webfont.woff2 copied.
source/assets/js/jquery.js copied.
Warning: Task "sass:dev" not found. Used --force, continuing.

Running "sync:dev" (sync) task

Running "sails-linker:devJs" (sails-linker) task
padding length 0
File "layout/_partial/script.ejs" updated.

Running "sails-linker:devCss" (sails-linker) task
padding length 4
File "layout/_partial/head.ejs" updated.

Running "replace:linker" (replace) task

Running "replace:cssFancybox" (replace) task

Running "replace:cssTranquilpeak" (replace) task

Done, but with warnings.
```

I have installed `grunt` and `bower` correctly according to your tips to @kaedea.
thanks for your help~

**Comment by LouisBarranqueiro** [comment]
@chenkaiC4 It seems that you have not the same problem that @kaedea has. Your probleme come from `node-sass`package. Try to delete the `node_modules` and run `npm install`. If it doesn't work, please, create an issue with your environment information (system and version of node, npm, and hexo)

**Comment by chenkaiC4** [comment]
@LouisBarranqueiro Thanks！I delete the `node_modules` and run `npm install` just as your tips, It now works!
^ ^ [my blog] (http://lispwow.com/)

**Comment by LouisBarranqueiro** [comment]
@chenkaiC4 goog news :)  
@kaedea Is it working?

**Comment by kaedea** [comment]
@LouisBarranqueiro 
yes it works, thanks.
I am reading your readme introduction. It is great.
