### ISSUE TITLE
Clicking on sandwitch button on iPhone and then clinking it again scrolls everything down

### ISSUE THREAD

**Issue by k155la3** [LouisBarranqueiro/tranquilpeak-hexo-theme#174]

**Comment by LouisBarranqueiro** [comment]
There is a bug yeah, but I got something different : it resize all the content. 

I'm on it

**Comment by LouisBarranqueiro** [comment]
I just fix the bug that I found, could you give me additional information (OS with version, browser wth version) to try to reproduce your bug.

**Comment by k155la3** [comment]
This is default Safari browser in iOS 9.2 on iPhone 5.

**Comment by LouisBarranqueiro** [comment]
come here : https://gitter.im/LouisBarranqueiro/tranquilpeak-hexo-theme please :)

**Comment by LouisBarranqueiro** [comment]
Fix with https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/commit/2dd290ae888e24e64d32133c0d171366853438f6
