### ISSUE TITLE
css style did not loaded

### ISSUE THREAD

**Issue by gilnuy** [LouisBarranqueiro/tranquilpeak-hexo-theme#175]
after hexo g,hexo s
![image](https://cloud.githubusercontent.com/assets/4455464/11740494/cebec8ae-a02d-11e5-9770-b8406f89116c.png)

**Comment by LouisBarranqueiro** [comment]
I bet that you downloaded the source, then you have to build the theme. Read developer documentation to know how to do that.

**Comment by gilnuy** [comment]
thanks, I will try it later.

**Comment by gilnuy** [comment]
thank you ~
it works, i did downloaded developer version.
now get the release version. it works.

**Comment by LouisBarranqueiro** [comment]
your welcome :)
