### ISSUE TITLE
Having trouble enabling read_more_message and go_to_message setting.

### ISSUE THREAD

**Issue by hugochan** [LouisBarranqueiro/tranquilpeak-hexo-theme#176]
Hi Louis,

First, thank you for your great job. I like your theme which I think is clean and elegant. But recently, I had trouble enabling read_more_message and go_to_message setting. Should I set them as true in the theme _config.yml file? It did not work for me. I could still see the whole articles in the homepage and there was no [continue reading] hyperlink, instead there was a [comment and share] hyperlink. 

Could you kindly tell me what was going wrong and how to enable this function.

Thanks,
Yu

**Comment by LouisBarranqueiro** [comment]
`read_more_message`and `go_to_message ` are editable in each languages files and they are string value.
`comment and share` link appears when there is no `<!-- more -->` and `<!-- excerpt -->` in post content.

**Comment by hugochan** [comment]
Thanks! It works.

**Comment by LouisBarranqueiro** [comment]
your welcome :)
