### ISSUE TITLE
How to set multiple tags in a post

### ISSUE THREAD

**Issue by hugochan** [LouisBarranqueiro/tranquilpeak-hexo-theme#178]
Hi Louis,

Could you tell me how to set multiple tags in a post?

Thanks,
Yu

**Comment by LouisBarranqueiro** [comment]
I recommend you to look into [source-blog-posts](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/tree/source-blog-posts/source/_posts) branch to see example of post and how to use some tags.

For multiple tags : 
``` yml
tags :
- tag_1
- tag_2
- tag_n
```

**Comment by hugochan** [comment]
Thanks!

**Comment by LouisBarranqueiro** [comment]
you're welcome :)

**Comment by 7pedroruizzz** [comment]
@LouisBarranqueiro 

Hi, any way to group tags separately in the tagcloud?

For example in a blogpost I have:

```
- tags: 
   - hello
   - hola
   - ciao
   - red
   - blue
   - white
``` 

And then from this generate two tagclouds with one having:
- hello
- hola
- ciao

and the second separate tagcloud having:
- red
- blue
- white

Possible?

Next step would be then to allow showing blogposts with 2 tags combined, for example "ciao + blue".
