### ISSUE TITLE
Profile link

### ISSUE THREAD

**Issue by steve2web** [LouisBarranqueiro/tranquilpeak-hexo-theme#19]
Hello, on profile pic link is /about replace to /#about, sorry my bad english! Thanks

**Comment by LouisBarranqueiro** [comment]
I don't understand what do you want. Can you explain more precisely please?

**Comment by LouisBarranqueiro** [comment]
Oh yes, I understood. I will fix this. thank you. :)

**Comment by LouisBarranqueiro** [comment]
this bug is fixed in [v1.0.4](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases). Thank you man :)

**Comment by steve2web** [comment]
You're welcome!
