### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by freshdgq** [LouisBarranqueiro/tranquilpeak-hexo-theme#2]
Hey, the URL of my blog is: xiaoshiguang10.com

**Comment by LouisBarranqueiro** [comment]
Thank you dude. You are the first. :)

**Comment by freshdgq** [comment]
lol, how can I add discus and google analysis?

**Comment by LouisBarranqueiro** [comment]
This issue is closed. Create another one to help other people if they have the same problem :)
