### ISSUE TITLE
mailto doesn't work

### ISSUE THREAD

**Issue by JiantaoFu** [LouisBarranqueiro/tranquilpeak-hexo-theme#20]
mailto settings in themes/tranquilpeak/_config.yml is like:

mailto://

and will generate "mailto://" in html, the correct format should be "mailto:"

https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/1e07e6835476256bf2f23d57ce36318f17651f43/layout/_partial/sidebar.ejs

change it to the following seems fixed this

                    <% if ( ((url_for(theme.sidebar[i][n].url).indexOf(config.url) < 0) && (url_for(theme.sidebar[i][n].url).indexOf('://') >= 0)) || (url_for(theme.sidebar[i][n].url).indexOf('mailto') >= 0)) { %>

**Comment by LouisBarranqueiro** [comment]
Thank you for reporting this bug. I will fix this right now :)

**Comment by LouisBarranqueiro** [comment]
This bug is fixed in [1.0.5](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.0.5) :)

**Comment by JiantaoFu** [comment]
It works now, thank you!

**Comment by LouisBarranqueiro** [comment]
your welcome :)
