### ISSUE TITLE
How to enable ToC

### ISSUE THREAD

**Issue by JiantaoFu** [LouisBarranqueiro/tranquilpeak-hexo-theme#21]
I saw your demo page has ToC, but i've no idea how to enable it.

Have tried put "<%- toc(page.content, {list_number: true}) %>" in tranquilpeak/layout/post.ejs, but this can't achieve the that like you are doing in your demo site.

Thanks in advance!

**Comment by LouisBarranqueiro** [comment]
what is ToC? Can you show me what do you want in the demo site with a screen?

**Comment by JiantaoFu** [comment]
Thanks, just wondering if that is generated by ToC markdown extension or do that manually like this:

# Table of Contents
1. [Example](#example)
2. [Example2](#example2)

## Example
## Example2

"<%- toc(page.content, {list_number: true}) %>" is supported by hexo now, see https://github.com/hexojs/hexo/issues/408, but when i do that, it seems it adding extra list number, and i can't remove it by {list_number: false}

![image](https://cloud.githubusercontent.com/assets/12674006/7920862/653aa520-0856-11e5-9937-6a135bc998bb.png)

OK, this might not relating to tranquilpeak, i will post issue for hexo, thanks!

**Comment by LouisBarranqueiro** [comment]
yes, it comes from the hexo-toc plugin or hexo.
