### ISSUE TITLE
All links are generated with absolute urls

### ISSUE THREAD

**Issue by zoharsacks** [LouisBarranqueiro/tranquilpeak-hexo-theme#25]
All links absolute, must deploy to debug

**Comment by LouisBarranqueiro** [comment]
can you explain your problem with more details please?

**Comment by zoharsacks** [comment]
1. generate site
2. run local hexo server
3. check link path
4. the path is absolute (e.g. http://zoharsacks.com/some_post) and not relative (/some_post)

**Comment by LouisBarranqueiro** [comment]
yeah, you're right. This is not a problem because domain is dynamic with general `_config.yml` but best practice recommend relative urls. I will fix this. thank you :)

**Comment by LouisBarranqueiro** [comment]
I will release the new version of tranquilpeak tomorow (v1.1).

**Comment by zoharsacks** [comment]
you are the best!!
and the template is to the point!! :)

I will test the new version once released

**Comment by LouisBarranqueiro** [comment]
I'm going to release it tomorrow. But Is it already fixed in `dev` branch with some others new features and improvements :) Sorry for the late

**Comment by zoharsacks** [comment]
mannn, you are great! thanks i really appreciate it.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.1.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.1.0) is here :)
