### ISSUE TITLE
can't add html in about/bio field

### ISSUE THREAD

**Issue by zoharsacks** [LouisBarranqueiro/tranquilpeak-hexo-theme#26]
1. user wishes to have url in his about section
2. user adds md link, outcome the link appears as text in about box
3. user adds html link, outcome the link appears as text in about box

sample here http://zoharsacks.com/

**Comment by LouisBarranqueiro** [comment]
It's a good idea. i'm on it :) I will render only markdown because it easy to use :)

**Comment by LouisBarranqueiro** [comment]
now, you can use markdown and html. I add the same thing for the job value if people wanna add a link of their company. :) This new feature will be available in version 1.1 today at 20:00 CEST

**Comment by LouisBarranqueiro** [comment]
now, you can use markdown and html. I add the same thing for the job value if people wanna add a link of their company. :) This new feature will be available in version 1.1 today at 20:00 CEST

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.1.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.1.0) is here :)
