### ISSUE TITLE
How can I remove the text in the sidebar and only show the icon?

### ISSUE THREAD

**Issue by gapplef** [LouisBarranqueiro/tranquilpeak-hexo-theme#27]
How can I remove the text in the sidebar and only show the icon? Just like this one:
![effect](http://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/2015/05/02/Check-official-user-documentation/archives-1.png)
btw: **user**  may be a better icon for "About me"

**Comment by LouisBarranqueiro** [comment]
1. Actually, you can't. The theme is responsive and this bar and only displayed when the user's screen is between 768px and 1023. To do that you have to change the CSS code and precisly the `source/_css/layout/_siderbar.scss` and apply the same style (medium style) for all screen medias
2. you can easily change the icons by finding the font-awesome icon class name and edit it in `_config.yml of the theme.

But your problem **1**, gave me an idea. Would like to have a value to choose the style (behavior) of the sidebar directly in `_config.yml`of the theme.

**Comment by gapplef** [comment]
wow, replied so fast, thank you!
A sample value in _config.yml to disable the display of text in sidebar is exactly what I want!
waiting for your update😊

**Comment by LouisBarranqueiro** [comment]
ok, i'm on it. :)

**Comment by LouisBarranqueiro** [comment]
That's it. Tomorrow, i'm going to release the new version (1.1) of the theme with this features and some other news

**Comment by gapplef** [comment]
So quick😊
Great job! Really appreciate your work

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.1.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.1.0) is here :)
