### ISSUE TITLE
left sidebar search icon is link is not relative

### ISSUE THREAD

**Issue by zoharsacks** [LouisBarranqueiro/tranquilpeak-hexo-theme#29]

**Comment by LouisBarranqueiro** [comment]
Exactly all links are absolute. i will fixed this.

**Comment by LouisBarranqueiro** [comment]
I just released [Tranquilpeak v1.1.1](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.1.1). This release fix this bug. Thanks you for your fast feedback mate! :)
