### ISSUE TITLE
A new Hexo theme for my blog based on tranquilpeak.

### ISSUE THREAD

**Issue by BelinChung** [LouisBarranqueiro/tranquilpeak-hexo-theme#3]
Hi, first of all, this is a great theme! Good job :)
I fork tranquilpeak and change it become my previous blog style.
Repo: https://github.com/BelinChung/tranquilpeak-hexo-theme
My blog: https://dearb.me

Just hope more people use tranquilpeak to build their own blog .

**Comment by LouisBarranqueiro** [comment]
Thank you man! I will add it. I hope too. Good to see that people fork and create their own theme :)
