### ISSUE TITLE
Highlight source code 

### ISSUE THREAD

**Issue by iPonyo** [LouisBarranqueiro/tranquilpeak-hexo-theme#30]
hi ! I want use transquilpeak to highlight source code, but when i write a new post, i dont't know how to use it in markdown. can you teach me ? Thank you very much ! Good luck !

**Comment by LouisBarranqueiro** [comment]
Consult [Hexo website - Codebock section](http://hexo.io/docs/tag-plugins.html#Example-1). :)

**Comment by iPonyo** [comment]
Thanks ! But if i insert html code , It does not work. Why ?
![code](https://cloud.githubusercontent.com/assets/2416322/8186756/c4b80fa4-147e-11e5-94bf-c6b709bf8b32.png)

**Comment by iPonyo** [comment]
Thanks ! But if i insert html code , It does not work. Why ?
![code](https://cloud.githubusercontent.com/assets/2416322/8186800/f76dd050-147e-11e5-9ff1-87a13a2a3183.png)

**Comment by LouisBarranqueiro** [comment]
Could you show me your error and source code please?

Here is HTML section from `highlighted-code-showcase.md`:
``` html
HTML

{% codeblock archives.html lang:xml archives.html %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<!--
*        Sample comment
-->
<HTML>
<head>
<title>WebStorm</title>
</head>
<body>
<h1>WebStorm</h1>
<p><br><b><IMG border=0 height=12 src="images/hg.gif" width=18 >
What is WebStorm? &#x00B7; &Alpha; </b><br><br>
</body>
</html>
{% endcodeblock %}
```

**Comment by iPonyo** [comment]
```
{% codeblock archives.html lang:html %}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//EN">
<!--
*        Sample comment
-->
<HTML>
<head>
<title>WebStorm</title>
</head>
<body>
<h1>WebStorm</h1>
<p><br><b><IMG border=0 height=12 src="images/hg.gif" width=18 >
What is WebStorm? &#x00B7; &Alpha; </b><br><br>
</body>
</html>
{% endcodeblock %}
```
highlight does not work ! No colors ! So i guess the problem is lang-language . Can you show me the full highlighted-code-showcase.md ? Email: 21887396@qq.com. Thanks !

**Comment by iPonyo** [comment]
The problem is resolved ! Thank you very much ! You are good man !  :+1:

**Comment by LouisBarranqueiro** [comment]
what was the problem?

**Comment by iPonyo** [comment]
The problem is that the programming language wrong .  Change lang-html to lang-xml, hightlight is ok !
Please forgive me, i'm not good at english !

**Comment by LouisBarranqueiro** [comment]
ok :D
