### ISSUE TITLE
edit article on localhost

### ISSUE THREAD

**Issue by yojo3000** [LouisBarranqueiro/tranquilpeak-hexo-theme#31]
how can I edit my article on localhost?
 I can open the site on localhost:4000,
 but when I click the tags or categories button it will redirect to github page

**Comment by LouisBarranqueiro** [comment]
You have to edit `url` variable in hexo `_config.yml` file.

**Comment by LouisBarranqueiro** [comment]
is it good?

**Comment by yojo3000** [comment]
I solved the problem
thanks a lot !

**Comment by LouisBarranqueiro** [comment]
your welcome :)
