### ISSUE TITLE
.md example files available?

### ISSUE THREAD

**Issue by digifu** [LouisBarranqueiro/tranquilpeak-hexo-theme#34]
I am trying to use hexo and your theme but I can't find any useful information how to use the internal link or the pull quotes. Are your .md files available for an example on how to use these functions?

**Comment by LouisBarranqueiro** [comment]
You have to use markdown language for blockquotes, links, images, headers, paragraph, etc.. For pullquotes, there is actually no equivalent in standard markdown, so use HTML language. For a right pullquote : `<div class="pullquote right">YOUR TEXT</div>`.

**Comment by LouisBarranqueiro** [comment]
I will add a section in user documentation to help user to writing articles :)

**Comment by LouisBarranqueiro** [comment]
I improved user documentation about Markdown syntax and tags plugins. Available in 2 days in the new version

**Comment by LouisBarranqueiro** [comment]
You can now use : 
``` markdown
{% pullquote [right] %}
content
{% endpullquote %}
```
