### ISSUE TITLE
How to adjust the width for the post?

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#36]
I would like to adjust the width for post because it seems to be a bit narrow in a big screen.
There seems to be no configuration for this. It is there a way to deal with this?

![enter image description here](https://lh3.googleusercontent.com/H5XFzPSMKrjQxzGGQBgxo6ZRvSEMfJ-ZzACO3sOt8Sc=w990-h487-no)

**Comment by LouisBarranqueiro** [comment]
1. Edit `max-width` value of `$main-content` map in `tranquilpeak/source/_css/utils/_variables.scss` file :  
``` scss
// Main content
$main-content: (
    'max-width':          750px,
    'padding-right-left': 20px,
);
```
2. Run `grunt build` or/and `grunt buildProd` to see changes
3. Enjoy :D

**Comment by kaedea** [comment]
Thanks, Louis.
Another, is it possible to set the sidebar to the right?

**Comment by LouisBarranqueiro** [comment]
Currently no, but it could be a new feature. Create a new issue to ask if other people would like to be able to do that :)

**Comment by kaedea** [comment]
Hey Louis, sorry to disturb.
As to super large screen, it seems not good simply setting a wider post-content. I think it is good to set a fixed 'max-width' for post-content just like what you have done.
Therefore, I am considering how about add a new sidebar behavior which show a wider and new-styled sidebar in super large screen.

![image](https://cloud.githubusercontent.com/assets/3963397/16032229/7f629588-3236-11e6-8bb5-d644eeec6ce8.png)

**Comment by jrbenito** [comment]
@kaedea ,

this is really a good thing to ask as new feature. Could you please open another issue?

Thanks

**Comment by LouisBarranqueiro** [comment]
@kaedea  @jrbenito It's a pitty to hide all sidebar menu with all this space. It takes 1 more actions to navigate with the menu. You would like exactly the same sidebar on the photo or it's just an example?

**Comment by kaedea** [comment]
@LouisBarranqueiro 
All right, I don't know exactly what **pitty** means. The wide sidebar I showed above is just an example. But I like this style (avatar + bio + links' icon).
Please consider this feature, as most Chinese coders like 1080p screen. The best way to keep a fixed-width post content in different screens is using a flexible sidebar.

**Comment by jrbenito** [comment]
@kaedea 

Do you need help to PR this? We can try merge in your code.
