### ISSUE TITLE
Google Analytics not working

### ISSUE THREAD

**Issue by keybits** [LouisBarranqueiro/tranquilpeak-hexo-theme#38]
Many thanks for this fantastic theme!

I've just set it up on my site here: http://www.keybits.net

The JavaScript for Google Analytics seems to be incorrect since it's not registering any hits there. The code Google is suggesting I should use is:

````
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64577670-1', 'auto');
  ga('send', 'pageview');

</script>
````
I can just edit `google-analytics.ejs` with the new function, but I thought I'd let you know in case this needs changing for a release.

**Comment by keybits** [comment]
Apologies - on reflection, it looks like the original snippet was OK and it was my error in testing. Feel free to close this issue if you don't wish to use the new analytics code above.

**Comment by LouisBarranqueiro** [comment]
oh, i was checking this. :D   
so they have updated the source code?

**Comment by keybits** [comment]
It looks like it - the above snippet is taken direct from my analytics console. I'm pretty sure the old version still works though. Here's an explanation:

https://developers.google.com/analytics/devguides/collection/analyticsjs/

**Comment by LouisBarranqueiro** [comment]
I will update the script in the next release. Thank you :)
