### ISSUE TITLE
theme install 

### ISSUE THREAD

**Issue by iPonyo** [LouisBarranqueiro/tranquilpeak-hexo-theme#4]
Your theme is very beautiful! 
But, I have a problem, deploy the blog to the GitHub, without any style and JS files  , the state is 404. please help me ! my blog address: http://iponyo.github.io/
Thanks !

**Comment by LouisBarranqueiro** [comment]
Thank you! :)  Which version did you have download? Production version already built or development version?

**Comment by iPonyo** [comment]
Hi !  As you known, i dowloaded development version ! Thanks for your help ! My blog is working !
Good luck !
