### ISSUE TITLE
Some way to navigate a long post

### ISSUE THREAD

**Issue by justincalleja** [LouisBarranqueiro/tranquilpeak-hexo-theme#40]
Assuming you have a long post, it would be nice to have some way to navigate the page. e.g. a table of contents at the top of the page.

Maybe a way to scroll to the top of the page is also in scope with this feature request.

**Comment by LouisBarranqueiro** [comment]
Currently, there is a Hexo plugin [hexo-toc](https://github.com/bubkoo/hexo-toc) which create a table of content at the top of the article with a `<!-- toc -->`. Useful when you start reading, but if you are in the middle of the article, or at the end, you have to go to the top. So, a good idea would be to enable for medium and large screen, a sidebar at the right of the article which contains the table of content. and for small screen, a button in bottom bar which show table of content. What do you think?

**Comment by justincalleja** [comment]
Hi Louis,

I'll give that plugin a shot when I have some time. Re the sidebar.. I'm not sure how well that would work if e.g. titles are long or there are too many nested levels (the latter could be limited, but what about the former? Truncating the title maybe?).

Do you know of any blogs using this approach (sidebar) for navigation?

The table of contents at the top seems reasonable. To get to it one could use browser shortcuts or we could add one of the many existing plugins for this.

I'll be giving the hexo-toc plugin a go. Thanks!

**Comment by LouisBarranqueiro** [comment]
Got it. :) try the toc plugin. I will start to implement this feature. I will take some screens to show you the UI :)

**Comment by justincalleja** [comment]
wow cheers Louis! hehe no need to bounce it off me, it's your theme.

My plan is to have a look at hexo-toc and to copy over the implementation from Hugo if hexo-toc doesn't fit the bill. I'll PR if it comes to it :)

**Comment by justincalleja** [comment]
hexo-toc is good enough I think. Thanks for pointing it out. (Hexo's toc helper was giving me duplicate numbers for the bullet points.. maybe I just didn't configure it well - but hexo-toc is not).

This is no longer an issue for me so I'm closing - not sure if you were working on something related to this?

**Comment by justincalleja** [comment]
btw, I added the following bit of CSS to the generated TOC:

div.post-content ul:first-child ul {
  margin: 0 0 0.5em 0;
}

as I thought the spacing was a bit too much (just in case anyone else thinks so too).

**Comment by kaedea** [comment]
Hi, Louis. Has this feature already been supported in the latest release version?

**Comment by justin-calleja** [comment]
@kaedea , table of content support (as far as I know), is available out of the box with Hexo (toc helper). There is also a Hexo plugin [hexo-toc](https://github.com/bubkoo/hexo-toc)

I ended up going with the Hexo toc helper, like so:

https://github.com/justincalleja/justincalleja.github.io/commit/898031a07300b8f96afff85ccb289dfa54854a2d

https://github.com/justincalleja/tranquilpeak-hexo-theme/commit/946388a049712f5d6ef8e3e2cf81bfc9f90d5a04

i.e. the theme now looks for `tocEnabled` in post meta-data and shows toc via helper.

Btw, regarding my previous comment in this thread:

> Hexo's toc helper was giving me duplicate numbers for the bullet points

you can get around this by:

```css
ol {
  list-style: none;
}
```

cheers
