### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by justincalleja** [LouisBarranqueiro/tranquilpeak-hexo-theme#41]
Add functionality to scroll to top in theme (for long posts).

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak 1.2.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.2.0) is released with this feature. Read [User documentation - display table of content](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#display-table-of-contents) to enjoy the best of this feature.

**Comment by justincalleja** [comment]
Epic! Many thanks :)

**Comment by LouisBarranqueiro** [comment]
Thank you for this idea! If you have some others :write them here - > #58

**Comment by justincalleja** [comment]
Nice! Will do :+1:
