### ISSUE TITLE
No syntax highlighting for HTML?

### ISSUE THREAD

**Issue by justincalleja** [LouisBarranqueiro/tranquilpeak-hexo-theme#44]
Haven't looked into this but noticed in passing that HTML is not getting highlighted (unlike other code snippets) when using the triple back ticks in markdown.

Tried using `{% codeblock [lang:html] %}` but getting the same results (highlighting for JS and some other syntaxes but not for HTML).

**Comment by justincalleja** [comment]
Gaah didn't bother checking existing issues sorry. So from #30 it's XML for HTML highlighting then.

**Comment by LouisBarranqueiro** [comment]
yes, you have to use `xml`. :D
