### ISSUE TITLE
Has extra settings for Swiftype?

### ISSUE THREAD

**Issue by marlonpatrick10** [LouisBarranqueiro/tranquilpeak-hexo-theme#49]
Hi Louis,

I setting the Swiftype search engine in my blog but in my Swiftype dashboard a get this message: Our crawler hasn’t downloaded any pages yet.

Is there any specific configuration in tranquilpeak for the Swiftype can scan my site?

I have no Robots.txt or Robots meta tags.

**Comment by LouisBarranqueiro** [comment]
All configuration is on Swiftype website side. I had no problems when I had my blog. Your blog has to be online and I think it's enough. Maybe Swiftype had a problem. Try to delete the engine and create a new one.

**Comment by LouisBarranqueiro** [comment]
Is that your problem is resolved?

**Comment by marlonpatrick10** [comment]
Hi Louis, I generate a sitemap with hexo plugin and create a robots.txt with foloowing content:
User-agent: *
Sitemap: my_blog_url/sitemap.xml

This way, Swiftype works well.

**Comment by LouisBarranqueiro** [comment]
cool :) Strangely, I have not had to do that
