### ISSUE TITLE
Gallery doesn't work if it's Google Photos URL

### ISSUE THREAD

**Issue by akiwarheit** [LouisBarranqueiro/tranquilpeak-hexo-theme#51]
Recently made a move to migrate from imgur to google photos

Apparently, gallery stops working with google photo URLs

http://hashtaghashtag.github.io/blog/2015/07/12/Shoot-Edit-Repeat/ (Google Photos URL)
http://hashtaghashtag.github.io/blog/2015/06/14/Let-s-start-an-adventure/ (Imgur)

Any advise? (aside from going back to imgur)

**Comment by LouisBarranqueiro** [comment]
1. I love your blog. :)  
2. About this problem, look url form imgur : `http://i.imgur.com/o9g09kT.jpg` and from google : `https://lh3.googleusercontent.com/0GLRzu0EY1W8xtUCfzmGCjgOS-jB1fLSSvzMzbUid7s=w1024-h686-no`. There is no extension at the end of the URL provide by Google. Fancybox maybe need an URL ended by an image extension (jpg, png, etcc
..). I will look at Fancybox code to verify this hypothesis

**Comment by akiwarheit** [comment]
1. Told my girlfriend; means a lot coming from the creator of the theme we're using :+1: 
2. I thought so; if it's on fancybox then you may close this. Thanks.

**Comment by LouisBarranqueiro** [comment]
Yes, my hypothesis is good! :) at the end of you url place `#.jpg` what ever the real file extension and it will work :)  
(e.g : `https://lh3.googleusercontent.com/0GLRzu0EY1W8xtUCfzmGCjgOS-jB1fLSSvzMzbUid7s=w1024-h686-no#.jpg` )

**Comment by LouisBarranqueiro** [comment]
I will write this tip in user documentation. Thanks you for feedback man :)

**Comment by akiwarheit** [comment]
It works! Thanks!

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak 1.2.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.2.0) fix this bug and no more need to add `#.jpg` at the end of url :)

**Comment by tintersniffer** [comment]
stedoney@hotmail.co.uk

**Comment by tintersniffer** [comment]
stedoney@hotmail.co.uk

**Comment by tintersniffer** [comment]
tintersniffer
