### ISSUE TITLE
Am getting `thumbnailImageUrl` is not defined exception when trying to display a post

### ISSUE THREAD

**Issue by justincalleja** [LouisBarranqueiro/tranquilpeak-hexo-theme#54]
This is happening here:

```
layout/_partial/post/header.ejs:21
    19|         <% } %>
    20|     <% } %>
 >> 21|     <% if (thumbnailImageUrl !== undefined) { %>
    22|         <div class="hide">
    23|             <img alt="" itemprop="image" src="<%= thumbnailImageUrl %>"/>
    24|         </div>
```

**Comment by LouisBarranqueiro** [comment]
You have currently the `dev` branch of the projet, this version is not currently stable.

**Comment by justincalleja** [comment]
Added this issue so I can reference it with a PR. Is that the way to go about things?

**Comment by LouisBarranqueiro** [comment]
yes. I wanted to improve the support of Swiftype (image of a post) but now I used open graph protocol to do that so i deleted this section of code. Check out the `dev`branch to see changes.

**Comment by justincalleja** [comment]
Ok cool, closing this issue then :)
