### ISSUE TITLE
Post Title and read_more_message and else link is wrong

### ISSUE THREAD

**Issue by carya** [LouisBarranqueiro/tranquilpeak-hexo-theme#57]
When I use the theme,  The main page look good, but when I want to browse a post or I want to see the posts under a tag, the link is wrong and show like this:  `Cannot GET /2015/07/17/index.html`, how can I fix this.

**Comment by LouisBarranqueiro** [comment]
Hi man, set `relative_link` to `false` in main `_config.yml` file. Which version of Hexo do you have?

**Comment by carya** [comment]
hexo: 3.1.1, mac10.10.4, thank you, this is fixed, but I found another problem, that is if i post code in the post, the line number of code is always 1,  not the actually line number

**Comment by LouisBarranqueiro** [comment]
I will release the new version of Tranquilpeak in some minutes. And I recommend to use Hexo 3.0.x. Hexo 3.1 have bugs with relative urls (like this one you have). Create an other issue, for the other problem. And please downgrade to Hexo 3.0.1 to have a better user experience :)

**Comment by carya** [comment]
OK, thank you so much
