### ISSUE TITLE
the description of picture is not just under of the picture

### ISSUE THREAD

**Issue by carya** [LouisBarranqueiro/tranquilpeak-hexo-theme#59]
When I use ![DescOfPicture][] to insert a picture, the DescOfPicture is not just under the picture, [like this](http://readus.org/2015/05/31/ios-dash-border-view/) , is this OK? I want to locate the description of picture under the picture, not center of the page, how can I do?

**Comment by LouisBarranqueiro** [comment]
what do you want 1 or 2?
**1* :  
![capture d ecran 2015-07-20 a 16 51 38](https://cloud.githubusercontent.com/assets/4705626/8778894/a0e55658-2f00-11e5-80ac-b41faf886942.png)

**2** :  
![capture d ecran 2015-07-20 a 16 58 07](https://cloud.githubusercontent.com/assets/4705626/8778892/9df39428-2f00-11e5-9df0-426531bde9bf.png)

**Comment by carya** [comment]
2 is OK, both the picture and description is on the left. I used markdown to insert a picture like this:

```
![UIView虚线边框示意图][]

[UIView虚线边框示意图]: http://readus-org.qiniudn.com/img/ios_dash_border_view.png
```

**Comment by LouisBarranqueiro** [comment]
I will improve the way that Tranquilpeak handle images in post (with fancybox too) and give more posibilities. I will release that in Tranquilpeak 1.2.1 at the end of the week. :)

**Comment by carya** [comment]
OK, I am eager to see it.

**Comment by LouisBarranqueiro** [comment]
How did you generated the tag `figure` around your image? that why I asked you what did you use to generete your image.
``` html 
<div class="figure">
    <img src="http://readus-org.qiniudn.com/img/ios_dash_border_view.png" alt="UIView虚线边框示意图">
    <p class="caption">UIView虚线边框示意图</p>
</div>
```

**Comment by carya** [comment]
I used `hexo-renderer-pandoc` to generate static html, the following is all my node modes:

![screen shot 2015-07-29 at 22 04 34](https://cloud.githubusercontent.com/assets/1852523/8959517/e080768c-363d-11e5-932a-d810edc14681.png)

**Comment by LouisBarranqueiro** [comment]
ok. I implemented a new tag : `image` for Tranquilpeak 1.3! Here is a preview of what you will be able to do with the new `image` tag and some css classes included :)
The tag will be : ```{% image [classes] /path/to/image [/path/to/thumbnail] [width of thumbnail] [height of thumbnail] [title text] %}```
![image-tag](https://cloud.githubusercontent.com/assets/4705626/8997139/555312ae-371e-11e5-987b-e3de6008cb08.gif)

**Comment by carya** [comment]
It looks amazing, when will version 1.3 be released?

**Comment by LouisBarranqueiro** [comment]
I'm waiting merge of i18n feature and i will release the new version. I hope in some days :)
I just added an other tag : `wide_image` to display image in full width like this :)
![capture d ecran 2015-08-02 a 11 46 07](https://cloud.githubusercontent.com/assets/4705626/9025627/7848421c-390c-11e5-81cb-73c5675e7964.png)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.3.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.3.0) is released :) check the user documentation about [image tag](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#image) and [wide image](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#wide-image)
