### ISSUE TITLE
Add my blog into showcase

### ISSUE THREAD

**Issue by haichao592** [LouisBarranqueiro/tranquilpeak-hexo-theme#6]
Hey, the URL of my blog is: haichao.me
This theme looks very nice and can be customized well.I use duoshuo instead of disqus for comments and the share group at the bottom of the article.
But I also found that the font makes me feel tired when I read my own blog.I don't know how to change the fonts and the highlight color. And the jacman's font and highlight color is more readable.
I'm looking forward to see a set of fonts and highlight colors.

**Comment by LouisBarranqueiro** [comment]
Sweet :) I appreciate.  Please create an other issue with the correct title  for your questions, to help other people if they have the same problem. I will answer it :)
