### ISSUE TITLE
CSS isn't work 

### ISSUE THREAD

**Issue by Sophiai** [LouisBarranqueiro/tranquilpeak-hexo-theme#60]
Hi Louis
I just download it,and modify the theme in _config.yml by changing theme variable to tranquilpeak.
When I run hexo server, I find css isn't work? Can you help me ?
![qq 20150722204911](https://cloud.githubusercontent.com/assets/8564932/8825739/eb4bb016-30b3-11e5-977e-36ec09e717f7.png)

**Comment by LouisBarranqueiro** [comment]
Did you download the built version or the source?

**Comment by Sophiai** [comment]
yes.
![image](https://cloud.githubusercontent.com/assets/8564932/8826206/7265bed6-30b7-11e5-93cd-675970c7ea30.png)

**Comment by LouisBarranqueiro** [comment]
yes, but which one? :D built-for-production version or source? in your browser check if there is only one file for js and one for css like that :  
![capture d ecran 2015-07-22 a 15 29 45](https://cloud.githubusercontent.com/assets/4705626/8826407/95333514-3086-11e5-88a0-52fdc7a382dc.png).  
If it not the case, you have source, and you have to build the theme grunt. To do that run : `grunt buildProd`. for more informations please check the [developer documentation](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/developer.md)

**Comment by Sophiai** [comment]
I got confused.
![image](https://cloud.githubusercontent.com/assets/8564932/8826546/d6ed8738-30b9-11e5-99f4-bff2da9e8565.png)
![image](https://cloud.githubusercontent.com/assets/8564932/8826556/df7122ca-30b9-11e5-9fbd-c51b5544f4d4.png)

**Comment by LouisBarranqueiro** [comment]
ok guy, you got the source. So you have to build the theme. Read this [build section of developer documentation](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/developer.md#build)

**Comment by Sophiai** [comment]
sorry,I ‘m new. When I run grunt default,something wrong.
![image](https://cloud.githubusercontent.com/assets/8564932/8827133/586e6dce-30bd-11e5-8fe8-403b8530bc50.png)

**Comment by Sophiai** [comment]
I run grunt buildProd,then run hexo server,css is working !
Thanks,Louis. ：）

**Comment by LouisBarranqueiro** [comment]
Your welcome :)
