### ISSUE TITLE
Minor css enhancement (for mobile devices)

### ISSUE THREAD

**Issue by h404bi** [LouisBarranqueiro/tranquilpeak-hexo-theme#62]
###### Word wrapping (post contents) (related: `word-wrap`, `white-space`, etc)

Some words missing, see: 
chrome debug
![chrome debug](https://cloud.githubusercontent.com/assets/5764917/8843977/464b58f2-3142-11e5-87cb-174a58fcbffd.jpg)

real device (Lumia 820)
![wp_ss_20150723_0001](https://cloud.githubusercontent.com/assets/5764917/8843996/93422622-3142-11e5-90d4-f21b88bfc660.png)

care about CJK words if you decide to enhance.

<hr/>

###### Buttons mismatch (`_partial/actions.ejs`) (happens on lower-resolution mobile devices)

chrome debug (iPhone 6, no problem)
![20150723141139](https://cloud.githubusercontent.com/assets/5764917/8844201/dde4aa5e-3144-11e5-9c7c-1f2dcc34c76f.jpg)

chrome debug (Lumia 520) & real device (Lumia 820, 4 inch), mismatch.
![20150723130052](https://cloud.githubusercontent.com/assets/5764917/8844219/0b75cc50-3145-11e5-8761-a8dbd3a85ca4.jpg)
![wp_ss_20150723_0002_meitu_2](https://cloud.githubusercontent.com/assets/5764917/8844222/15171eb2-3145-11e5-84f7-050adf6067ae.jpg)

That's all. :whale:

**Comment by LouisBarranqueiro** [comment]
Thank you man for feedback. I will fix this. It will be release in 1.2.1 at the end of the week :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.3.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.3.0) is released and fix that :)
