### ISSUE TITLE
one page two description   meta

### ISSUE THREAD

**Issue by gopheryu** [LouisBarranqueiro/tranquilpeak-hexo-theme#63]
+  head set :  \<meta name="description" content="<%= config.title %>"\>   

+ from og
   result += og('og:description', description);

**Comment by LouisBarranqueiro** [comment]
you're right.

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak v1.3.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.3.0) is released :)
