### ISSUE TITLE
Add Google adsense

### ISSUE THREAD

**Issue by jniltinho** [LouisBarranqueiro/tranquilpeak-hexo-theme#67]
Please add new feature Google adsense

Cool Theme, my Blog -> http://blog.linuxpro.com.br/

Thank's

**Comment by LouisBarranqueiro** [comment]
Could you be more precise please? what do you want exactly?

**Comment by jniltinho** [comment]
Like this http://www.voidynullness.net/blog/2015/06/25/add-recent-posts-list-to-pelican-blog/

place for adsense top and bottom

**Comment by LouisBarranqueiro** [comment]
This feature doesn't improve the theme itself in terms of UI/UX so I can't had it to the Tranquilpeak 1.3 features sorry. But fork the project and implement it. It seems to be easy.
