### ISSUE TITLE
Is it possible to dynamically change the width of post area?

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#68]
The width of the post looks perfect for Monitor with Resolution 1336 × 768. But it looks too narrow in Monitor with Resolution 1920 × 1080.

Is that possible to dynamically change the width of post area, in order to make the post look wider?

**Comment by LouisBarranqueiro** [comment]
yes, you have to edit in `source/_css/utils/_variables.scss` this part:  
``` scss
// Main content
$main-content: (
    'max-width':          780px,
    'padding-right-left': 20px,
);
```

Replace max-with by a value in %. If you want a different behavior for small, medium and large screens, you have to create media queries in `source/_css/components/_main-content.scss`

**Comment by kaedea** [comment]
Should I edit this in the dev version?

**Comment by LouisBarranqueiro** [comment]
why in `dev` version? fork the project and create your own version :)

**Comment by kaedea** [comment]
No, I mean should I have to clone your project, edit `max-width` and build the theme I want.
Or just edit `max-width` in the release one so that I do not need to build it.

**Comment by LouisBarranqueiro** [comment]
In both case you will have to build the theme.

**Comment by kaedea** [comment]
:) thx Louis

**Comment by LouisBarranqueiro** [comment]
your welcome :)
