### ISSUE TITLE
how to add images

### ISSUE THREAD

**Issue by carloscarcamo** [LouisBarranqueiro/tranquilpeak-hexo-theme#69]
Hello, 

I have a little question, I would like to include some images on a post, for example:

```html
<a href="link" target="_blank">
  <img src="./assets/images/css3.png" alt="css3" width="100">
</a>
```
is there any variable or something for the assets folder, a variable that can be use when writing a post in markdown?

Thanks in advance!

**Comment by LouisBarranqueiro** [comment]
Hi man,
1. Enable post assets folder feature : [user documentation - enable post assets folder](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#enable-post-assets-folder)
2. Place your images (css.png) in the right folder of your post in `source/_posts/your-post-folder` 
3. Use relative path, so the url will be : css3.png

E.g : 
``` html
<a href="link" target="_blank">
  <img src="css3.png" alt="css3" width="100">
</a>
```

If you are new to Hexo please, read Hexo documentation and Tranquilpeak documentation to get the best of them :)

Tranquilpeak 1.3 will be release in some days with new tags to help user to add images in post :)

**Comment by carloscarcamo** [comment]
awesome! thanks!
