### ISSUE TITLE
Use sidebar overflow:auto instead scroll

### ISSUE THREAD

**Issue by Axxiss** [LouisBarranqueiro/tranquilpeak-hexo-theme#7]
Forcing the sidebar to overflow:auto will show scrollbars even when they aren't necessary, changing it to auto will show it only when they're needed.

**Comment by LouisBarranqueiro** [comment]
you're right. Can you fix that on the dev branch? :)

**Comment by Axxiss** [comment]
Sure, will send a PR asap.

**Comment by LouisBarranqueiro** [comment]
Thank you dude

**Comment by Axxiss** [comment]
Fixed in #9
