### ISSUE TITLE
Documentation for Changing Sidebar Color

### ISSUE THREAD

**Issue by ReservedDeveloper** [LouisBarranqueiro/tranquilpeak-hexo-theme#71]
Is there any way to change the sidebar color? I tried looking through the documentation, but couldn't find anything. I also tried tweaking values in source/_css/utils/_variables.scss without much success. If some documentation could be added for that, it'd be appreciated!

**Comment by LouisBarranqueiro** [comment]
if you modified the theme, you are considered as a developer. I can't write a docs to explain how to modify each components.In developer doc, There is the architecture of the project (stylesheets precisely), you can see that there is a file `source/_css/layout/_sidebar.scss` where you can stylize the sidebar :)

**Comment by ReservedDeveloper** [comment]
> if you modified the theme, you are considered as a developer. 

Indeed @LouisBarranqueiro. Instead of hacking away at it and seeing what sticks, suppose I need to become a bit more informed on SCSS and some of the tooling involved. Thanks for the quick feedback!

**Comment by LouisBarranqueiro** [comment]
in [developper documentation - stylesheets section](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/developer.md#stylesheets), There is 2 links which can helps you to understand of SCSS works. About CSS, I think that [w3school](http://www.w3schools.com/css/) can helps you to understand what you need to realize what you want :)
