### ISSUE TITLE
When I use 1.3.0, there is no css on generated site

### ISSUE THREAD

**Issue by carya** [LouisBarranqueiro/tranquilpeak-hexo-theme#73]
When I use 1.3.0, and use `hexo server` to preview, it looks there is no css, as follows:

![screen shot 2015-08-11 at 20 53 53](https://cloud.githubusercontent.com/assets/1852523/9197963/2e11818e-406b-11e5-91c0-86edcce9d4a6.png)

**Comment by GonzaloAlvarez** [comment]
Have you downloaded bower dependencies?

```
bower install
```

**Comment by LouisBarranqueiro** [comment]
I think you have downloaded the source code and not a built version. Read developer documentation to build the theme

**Comment by carya** [comment]
When I download the built version, it looks ok, thank you.
