### ISSUE TITLE
The picture and it's description is wrong placed

### ISSUE THREAD

**Issue by carya** [LouisBarranqueiro/tranquilpeak-hexo-theme#76]
Now I used 1.3.0, When I insert a picture as follows:

```
![UIView虚线边框示意图][]

[UIView虚线边框示意图]: http://readus-org.qiniudn.com/img/ios_dash_border_view.png
```

But the generate site is as follows, the picture and it's description is not aligned.

![screen shot 2015-08-13 at 07 42 55](https://cloud.githubusercontent.com/assets/1852523/9239536/38018458-418f-11e5-9ce5-73a987a0842a.png)

When I use [light theme](https://github.com/hexojs/hexo-theme-light), all looks ok, what wrong with my configuration?

**Comment by LouisBarranqueiro** [comment]
You have to use image tag : [user documentation - image tag](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#image) :)

**Comment by LouisBarranqueiro** [comment]
Is it ok? :)
