### ISSUE TITLE
files is 404

### ISSUE THREAD

**Issue by akar1nchan** [LouisBarranqueiro/tranquilpeak-hexo-theme#77]
GET http://0.0.0.0:4000/assets/css/font-awesome.css 
0.0.0.0/:39 GET http://0.0.0.0:4000/assets/css/jquery.fancybox.css 
0.0.0.0/:40 GET http://0.0.0.0:4000/assets/css/jquery.fancybox-thumbs.css 
0.0.0.0/:41 GET http://0.0.0.0:4000/assets/css/tranquilpeak.css 
0.0.0.0/:400 GET http://0.0.0.0:4000/assets/js/jquery.js 
0.0.0.0/:401 GET http://0.0.0.0:4000/assets/js/jquery.fancybox.js 
0.0.0.0/:402 GET http://0.0.0.0:4000/assets/js/jquery.fancybox-thumbs.js 
0.0.0.0/:403 GET http://0.0.0.0:4000/assets/js/tranquilpeak.js 404 (Not Found)

**Comment by LouisBarranqueiro** [comment]
Did you download the source or the "binaries"? I think you have download the source and you didn't read the developer documentation. Everything is explained to get all dependencies and build the theme.

**Comment by socoolby** [comment]
I met the same problem too. And when I was use other theme,Ii's normal.

**Comment by akar1nchan** [comment]
@socoolby 

 I download missing files from demo pages. that's fixed

I wish theme's author add these files into /theme/tranquilpeak-hexo-theme/source  (notice path problem)


this theme so pretty~ i like it~

Thank U~

**Comment by socoolby** [comment]
@akar1nchan THX! It's working.

**Comment by LouisBarranqueiro** [comment]
that's not the right way lol :D You juste have to get all dependencies and build the theme : 
1. run `npm install`
2. run `bower install`
3. run `npm install grunt-cli -g`
4. run `grunt `default`

and before deploy on production :  run `grunt buildProd` to optimize assets and reduce http requests

**Comment by akar1nchan** [comment]
@LouisBarranqueiro Thanks for your detailed answer .
@socoolby  Enjoy~

**Comment by LouisBarranqueiro** [comment]
Your welcome :)

**Comment by Imyssed** [comment]
(手动抠鼻)这个问题当初烦了我一个宝贵的下午 当时我直接从GitHub下了master分支用着 然后文件报错
不过后来我才发现...source里面的内容都是加了_的...
这意味着什么?Hexo会跳过处理!
然而即使你去掉_也没有用...看看源码,原来都放在assets里啦!快快创建...继续报错...
最后发现releases里的版本是已经整合好了的
这时终于明白了tasks里文件的作用...
打开开发者手册终于明了一切了
到主题目录里`npm i grunt-cli`和`npm i`,然后再`grunt build`一下才能弄出文件来
(手动抠鼻)真复杂

**Comment by xenglog** [comment]
@ghost 可算找到中国人了 大哥他demo用的哪个分支啊 T - T  master和demo差远了啊

**Comment by xxxxavier** [comment]
@AudienceX 他的master分支里是不带css和js的文件的，他的user document里有一个项目的压缩包，用哪个就好，实在是不明白他为什么这么做
