### ISSUE TITLE
How can I remove facebook or twitter share links at end of post?

### ISSUE THREAD

**Issue by chenlai** [LouisBarranqueiro/tranquilpeak-hexo-theme#78]
I want remove share post on facebook or twiitter, change to another , like [WeChat](https://web.wechat.com/), [WeiBo](http://weibo.com/).

Right links in below picture.
![](http://7xkzbi.com1.z0.glb.clouddn.com/Screenshot%20from%202015-08-17%2013%3A41%3A02.png)

Thanks,

**Comment by LouisBarranqueiro** [comment]
There is currently no features to do that so you have to edit `layout/_partial/post/share-options.ejs` file.

**Comment by LouisBarranqueiro** [comment]
Is it good?

**Comment by mxxiv** [comment]
hi, I tried to change the file, but it didn't make any effect, what am I gonna do now?

**Comment by LouisBarranqueiro** [comment]
you have to build the theme. please read developer documentation

**Comment by mxxiv** [comment]
Thank you
This problem has been solved.
I want to change the theme of the Markdown display style, how to do it

**Comment by LouisBarranqueiro** [comment]
I don't understand. what is "Markdown display style"?

**Comment by mxxiv** [comment]
Sorry, my english is not very good.
I mean Objective-C code is not highlighted .. and how to set the background color of the code block

**Comment by mxxiv** [comment]
It's all done.
Thank you!

**Comment by LouisBarranqueiro** [comment]
Good news :)
