### ISSUE TITLE
The "###" markdown singal does not work with release 1.3.0

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#81]
![](https://lh3.googleusercontent.com/-sNsXlzLGdSA/VdQqgU636rI/AAAAAAAABKk/YRPT3Suxex4/s800/BaiduShurufa_2015-8-19_14-51-52.jpg "")

**Comment by LouisBarranqueiro** [comment]
Could you add source code of the article, **hexo** version and **hexo-renderer-marked** version please?

**Comment by kaedea** [comment]
> C:\Users\estel>hexo version
> hexo-cli: 0.1.7
> os: Windows_NT 6.3.9600 win32 x64
> http_parser: 2.3
> node: 0.12.2
> v8: 3.28.73
> uv: 1.4.2-node1
> zlib: 1.2.8
> modules: 14
> openssl: 1.0.1m



###大名鼎鼎的[Genymotion](https://www.genymotion.com/)

[Genymotion](https://www.genymotion.com/)是一款顺畅和容易（fast and easy-to-use）使用的Android模拟器，可以用来运行和调试你的APP。[Genymotion](https://www.genymotion.com/) 来自于[AndroVM](http://androvm.org/blog/) 这个开源项目，基于 x86 和 [VirtualBox](https://www.virtualbox.org/)，支持 OpenGL 加速，可以用于 `Mac/Win/Linux`。最近发布了新版，支持了 Android2.3/4.3，新增了拖拽安装 apk，移除了 Google 市场（后面提供解决方案）。另外增加了功能更丰富的[付费版](https://shop.genymotion.com/index.php?controller=order-opc)，个人可以继续使用免费版。

####特点

 1. 超级流畅；
 2. 支持拖拽安装APK；
 3. 有多种Android系统版本和设备类型供选择；
 4. 能模拟手机的旋转、充电情况、GPS数据等物理数据；

It looks that the # singal does not work here in comment either. Do I use it in a wrong way?

**Comment by LouisBarranqueiro** [comment]
go in your `package.json` file and get **hexo** version and **hexo-renderer-marked** please. I test your code, and it works fine with **hexo** : 3.1.1 and **hexo-renderer-marked** : 0.2.5   
![capture d ecran 2015-08-19 a 11 08 14](https://cloud.githubusercontent.com/assets/4705626/9352652/446b3ea4-4663-11e5-93de-3b08dd4eb1d6.png)

**Comment by kaedea** [comment]
Thanks!

**Comment by jin5354** [comment]
Got same problem.  hexo 3.1.1 and hexo-renderer-marked 0.2.5.

**strong**  
- list
 ```code```.etc  all work fine, only # singal doesn't work

**Comment by LouisBarranqueiro** [comment]
@jin5354 copy your source code please

**Comment by jin5354** [comment]
@LouisBarranqueiro  I found the reason. There should be a space between '#' and letters.

"###word" can't work. "### word"works.  Is this space absolutely necessary? I'm migrating hexo from 2.x to 3. The old hexo can correctly recognize '###word'.

Thanks for your attention. Awesome theme!

**Comment by h404bi** [comment]
@jin5354 not absolutely, some parser can render it, but with space is the correct markdown syntax. see [Daring Fireball: Markdown Syntax Documentation][1] or [Mastering Markdown &middot; GitHub Guides][2].


[1]: https://daringfireball.net/projects/markdown/syntax#header
[2]: https://guides.github.com/features/mastering-markdown/#syntax

**Comment by kaedea** [comment]
Do you know how to upgrade the `hexo-renderer-marked` dependency version in HEXO? Mine is `0.2.4`

**Comment by jin5354** [comment]
@kaedea Just run ```npm i hexo-renderer-marked@0.2.5```

**Comment by LouisBarranqueiro** [comment]
I seems that the new hexo-renderer-marked required a between `#` and the title. As @h404bi saidthe correct markdown syntax require a space.

**Comment by jin5354** [comment]
Thanks for your help.
