### ISSUE TITLE
The scroller at about page

### ISSUE THREAD

**Issue by jin5354** [LouisBarranqueiro/tranquilpeak-hexo-theme#82]
#about {
  display: none;
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(17, 26, 35, 0);
  text-align: center;
  line-height: 100%;
  overflow: scroll;    --> hidden?
  z-index: 30; 
}

I think the empty scroller is useless, the background Image can't fill the viewport full.

**Comment by jin5354** [comment]
if you want to eliminate the background image's vibration caused by scroller's disappear, maybe '100vw' width is better.

#cover {width:100vw;}
#about {overflow: hidden;}

**Comment by LouisBarranqueiro** [comment]
I had `overflow: scroll` to scroll  the about card in case of the about card is long on mobile devices
