### ISSUE TITLE
Make the sidebar be configurable to the right.

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#83]
Now the sidebar is fixed to the left. As most people use mouse with the right hand, it is supposed suitable to reach the sidebar from right. Could it be considerd to make this be configurable in production tranquilpeak-hexo-theme? This may take a lot of work because we need to replace the thumbnail of the post in index page as well. Anyway, this is just an advice and I will try to do this in the dev theme myself.

**Comment by LouisBarranqueiro** [comment]
Yes, it can be a good feature. HTML, CSS and JS of sidebar is well built so it pretty easy to implement this feature but you have to edit a lot of files. Good luck :)
