### ISSUE TITLE
Offer the markdown sourcecode of the posts in your demo blog?

### ISSUE THREAD

**Issue by kaedea** [LouisBarranqueiro/tranquilpeak-hexo-theme#86]
Could you please offer the markdown sourcecode of the posts in your demo blog?
[demo](http://louisbarranqueiro.github.io/tranquilpeak-hexo-theme/)
For 2 reasion:
- As sample for those who wanna use your theme. Code is the best tutorial.
- For those who wanna edit your theme(like me). These sample posts help a lot for debug.

**Comment by LouisBarranqueiro** [comment]
Yeah, I will do that! :) Other persons had already asked me the source code.

**Comment by kaedea** [comment]
Would you please offer it to me via email `kidhaibara@gmail.com`?

**Comment by LouisBarranqueiro** [comment]
All sources are on [source-blog-post](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/tree/source-blog-posts) branch :)

**Comment by kaedea** [comment]
Good Job!
