### ISSUE TITLE
Search bar and default search "engine"

### ISSUE THREAD

**Issue by eephyne** [LouisBarranqueiro/tranquilpeak-hexo-theme#93]
Hello

I see you use swiftype to search but what If I just want to use the default (I think its the default?) google site:XXX search system ? With an search field showing when hovering on the search button ?

I didn't see anything to activate that so I assume you simply removed it ?

**Comment by LouisBarranqueiro** [comment]
There is no default search engine. You only have possibility to use swiftype. I removed nothing (I don't understand : "*you simply removed it ?*", if you want to use google search engine, you have to implement this feature.

**Comment by eephyne** [comment]
Ok my bad, since I saw this system on many others themes I assumed it was kind of default.

thanks for your speed :)

**Comment by LouisBarranqueiro** [comment]
no, but i recommend you to use Swiftype. Easy to setup and easy to use. You can easily and deeply customize search results. :)

**Comment by eephyne** [comment]
I will look into it

**Comment by eephyne** [comment]
I don't find it so easy, beside the fact thats a paid service, I can't even get the code (so the key too) until some pages and data have been crawled by their search engine

**Comment by LouisBarranqueiro** [comment]
wait 15mins, and it will be good. free account is enough to handle 1 blog

**Comment by oliviafu** [comment]
it's no longer free now
