### ISSUE TITLE
fr-FR translation if you want

### ISSUE THREAD

**Issue by eephyne** [LouisBarranqueiro/tranquilpeak-hexo-theme#95]
If you want to add it, here's my translation of the langage file in fr

https://gist.github.com/eephyne/0f866a3de982c9a93c34

**Comment by LouisBarranqueiro** [comment]
It's a shame because I'm french, and i didn't do it :D Create a pull request :)

**Comment by eephyne** [comment]
Too lazy to fork the repo (shame on me).and I've made several modification beside that
