### ISSUE TITLE
How can I hide the content before <!-- more --> ?

### ISSUE THREAD

**Issue by callmewhy** [LouisBarranqueiro/tranquilpeak-hexo-theme#98]
Hey, I don't want what I say before `<!-- more -->` showed in my post.

How can I hide it?

**Comment by LouisBarranqueiro** [comment]
Currently, you can't do it. In the next version, you will be able to do that with `excerpt` variable in front matter. please read #89 for more information.

**Comment by callmewhy** [comment]
Oh thanks! Sorry I haven't see this issue.

Excited!
